import type { CourseContent } from "./types.js";

export const chessContent: CourseContent = {
  slug: "chess",
  titleUk: "Шахи",
  titleEn: "Chess",
  descriptionUk: "Теорія, тактичні задачі та онлайн-партії.",
  descriptionEn: "Theory, puzzles, and live games with other players.",
  icon: "♟️",
  color: "#1B1B1B",
  units: [
    {
      slug: "rules",
      titleUk: "Правила",
      titleEn: "Правила",
      lessons: [
        {
          slug: "board-pieces",
          titleUk: "Дошка та фігури",
          titleEn: "Дошка та фігури",
          baseXp: 15,
          difficulty: 1,
          isFree: true,
          exercises: [
            {
              id: "ch-1-1",
              type: "chess_lesson",
              promptUk: "Початкова позиція",
              fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
              notesUk:
                "Білі ходять першими. Король — найважливіша фігура; мета гри — поставити мат королю суперника.",
              quiz: {
                q: "Хто ходить першим?",
                options: ["Чорні", "Білі", "Той, хто виграв жереб", "Будь-хто"],
                correctIndex: 1,
              },
            },
            {
              id: "ch-1-2",
              type: "mcq",
              promptUk: "Яка фігура ходить літерою «Г»?",
              options: ["Слон", "Тура", "Кінь", "Пішак"],
              correctIndex: 2,
            },
          ],
        },
        {
          slug: "king-check",
          titleUk: "Шах і мат",
          titleEn: "Шах і мат",
          baseXp: 18,
          difficulty: 1,
          isFree: true,
          exercises: [
            {
              id: "ch-2-1",
              type: "mcq",
              promptUk: "Що таке шах?",
              options: [
                "Атака на короля",
                "Взяття тури",
                "Рокіровка",
                "Хід пішаком на 2 клітинки",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-2-2",
              type: "chess_lesson",
              promptUk: "Мат — коли король під шахом і немає захисту",
              fen: "7k/5Q2/6K1/8/8/8/8/8 w - - 0 1",
              notesUk: "Ферзь на f7 захищений королем — чорний король у маті (після правильної постановки).",
              quiz: {
                q: "Мат означає:",
                options: [
                  "Гру закінчено, король під невідворотним шахом",
                  "Можна здатися",
                  "Нічия",
                  "Рокіровку",
                ],
                correctIndex: 0,
              },
            },
          ],
        },
        {
          slug: "special-moves",
          titleUk: "Спеціальні ходи",
          titleEn: "Спеціальні ходи",
          baseXp: 18,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "ch-3-1",
              type: "mcq",
              promptUk: "Рокіровка — це:",
              options: [
                "Хід королем і турою в одному ході",
                "Взяття на проході",
                "Перетворення пішака",
                "Подвійний шах",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-3-2",
              type: "mcq",
              promptUk: "Пішак, досягнувши 8-ї горизонталі:",
              options: ["Зникає", "Перетворюється", "Стоїть далі", "Стає королем"],
              correctIndex: 1,
            },
          ],
        },
      ],
    },
    {
      slug: "tactics",
      titleUk: "Тактика",
      titleEn: "Тактика",
      lessons: [
        {
          slug: "mate-in-1-a",
          titleUk: "Мат в 1: частина А",
          titleEn: "Мат в 1: частина А",
          baseXp: 20,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "ch-p1",
              type: "chess_puzzle",
              promptUk: "Знайдіть мат в 1 хід (білі)",
              fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
              solutionSans: ["Re8#"],
              difficulty: 1,
            },
            {
              id: "ch-p2",
              type: "chess_puzzle",
              promptUk: "Мат в 1: ферзь",
              fen: "r1bqkb1r/pppp1Qpp/2n2n2/4p3/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 0 1",
              solutionSans: ["Qxf7#"],
              difficulty: 1,
            },
          ],
        },
        {
          slug: "mate-in-1-b",
          titleUk: "Мат в 1: частина Б",
          titleEn: "Мат в 1: частина Б",
          baseXp: 20,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "ch-p3",
              type: "chess_puzzle",
              promptUk: "Мат турою",
              fen: "7k/6pp/8/8/8/8/8/R5K1 w - - 0 1",
              solutionSans: ["Ra8#"],
              difficulty: 1,
            },
            {
              id: "ch-p4",
              type: "chess_puzzle",
              promptUk: "Мат двома турами (класика)",
              fen: "4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1",
              solutionSans: ["Ra8#"],
              difficulty: 2,
            },
          ],
        },
        {
          slug: "forks",
          titleUk: "Вилки",
          titleEn: "Вилки",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "ch-p5",
              type: "chess_puzzle",
              promptUk: "Кінь бере з вилкою (проста позиція)",
              fen: "r1bqkb1r/pppp1ppp/2n2n2/4p1N1/2B1P3/8/PPPP1PPP/RNBQK2R w KQkq - 0 1",
              solutionSans: ["Nxf7"],
              difficulty: 2,
            },
            {
              id: "ch-p6",
              type: "mcq",
              promptUk: "Вилка — це:",
              options: [
                "Одна фігура атакує дві цілі",
                "Обмін ферзями",
                "Рокіровка під шахом",
                "Пат",
              ],
              correctIndex: 0,
            },
          ],
        },
        {
          slug: "pins-skewers",
          titleUk: "Зв'язки",
          titleEn: "Зв'язки",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "ch-p7",
              type: "mcq",
              promptUk: "Зв'язка (pin) — коли фігура:",
              options: [
                "Не може рухатись без відкриття ціннішої фігури",
                "З'їдає дві фігури",
                "Робить рокіровку",
                "Стає ферзем",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-p8",
              type: "chess_puzzle",
              promptUk: "Знайдіть сильний хід (шах)",
              fen: "r1bqk2r/pppp1ppp/2n2n2/2b1p1N1/2B1P3/3P4/PPP2PPP/RNBQK2R w KQkq - 0 1",
              solutionSans: ["Nxf7"],
              difficulty: 3,
            },
          ],
        },
        {
          slug: "more-puzzles",
          titleUk: "Ще задачі",
          titleEn: "Ще задачі",
          baseXp: 25,
          difficulty: 3,
          exercises: [
            {
              id: "ch-p9",
              type: "chess_puzzle",
              promptUk: "Мат ферзем",
              fen: "5k2/8/6K1/8/8/8/5Q2/8 w - - 0 1",
              solutionSans: ["Qf7#"],
              difficulty: 2,
            },
            {
              id: "ch-p10",
              type: "chess_puzzle",
              promptUk: "Мат в 1 (ладья + король)",
              fen: "7k/8/6K1/8/8/8/8/7R w - - 0 1",
              solutionSans: ["Rh8#"],
              difficulty: 1,
            },
          ],
        },
        {
          slug: "back-rank-mates",
          titleUk: "Мати на останній горизонталі",
          titleEn: "Мати на останній горизонталі",
          baseXp: 24,
          difficulty: 3,
          exercises: [
            {
              id: "ch-p11",
              type: "chess_puzzle",
              promptUk: "Back-rank мат",
              fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
              solutionSans: ["Re8#"],
              difficulty: 2,
            },
            {
              id: "ch-p12",
              type: "mcq",
              promptUk: "Back-rank mate — це:",
              options: [
                "Мат турою/ферзем на 8-й (1-й) горизонталі",
                "Мат конем",
                "Рокіровка",
                "Пат",
              ],
              correctIndex: 0,
            },
          ],
        },
        {
          slug: "opening-ideas",
          titleUk: "Ідеї дебюту",
          titleEn: "Ідеї дебюту",
          baseXp: 20,
          difficulty: 2,
          exercises: [
            {
              id: "ch-op1",
              type: "chess_lesson",
              promptUk: "Контроль центру",
              fen: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1",
              notesUk:
                "1.e4 займає центр і відкриває шляхи ферзю та слону. Мета дебюту: центр, розвиток, безпека короля.",
              quiz: {
                q: "Основна мета дебюту?",
                options: [
                  "Центр, розвиток, безпека короля",
                  "Тільки ходити пішаками",
                  "Здатися на 5-му ході",
                  "Не розвивати фігури",
                ],
                correctIndex: 0,
              },
            },
            {
              id: "ch-op2",
              type: "mcq",
              promptUk: "Чому важлива рокіровка?",
              options: [
                "Ховає короля й активує туру",
                "Дає зайвого ферзя",
                "З'їдає дві фігури",
                "Заборонена в бліці",
              ],
              correctIndex: 0,
            },
          ],
        },
      ],
    },
    {
      slug: "endgames-intro",
      titleUk: "Ендшпіль: вступ",
      titleEn: "Endgame intro",
      lessons: [
        {
          slug: "opposition-basics",
          titleUk: "Опозиція: основи",
          titleEn: "Opposition basics",
          baseXp: 18,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "ch-eg-op1",
              type: "mcq",
              promptUk: "Опозиція — це коли королі:",
              promptEn: "Opposition is when kings:",
              options: [
                "Стоять один навпроти одного через клітинку",
                "На одній клітинці",
                "Завжди на a1 і h8",
                "Рокіруються одночасно",
              ],
              correctIndex: 0,
              explanationUk: "Хто «віддає» опозицію, часто пропускає короля суперника.",
              explanationEn: "The side that yields opposition often lets the enemy king in.",
            },
            {
              id: "ch-eg-op2",
              type: "mcq",
              promptUk: "У король+пішак vs король ключ — це:",
              promptEn: "In K+P vs K the key is often:",
              options: [
                "Король попереду / підтримка пішака + опозиція",
                "Лише ходи ферзем",
                "Завжди здатися на 1-му ході",
                "Ігнорувати короля суперника",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-eg-op3",
              type: "chess_lesson",
              promptUk: "Уявіть опозицію",
              promptEn: "Picture opposition",
              fen: "8/8/8/4k3/8/4K3/8/8 w - - 0 1",
              notesUk: "Білий король на e3, чорний на e5 — класична вертикальна опозиція.",
              notesEn: "White Ke3 vs black Ke5 is classic vertical opposition.",
              quiz: {
                q: "Відстань між королями в опозиції?",
                options: ["1 клітинка між ними", "0 (атака)", "3+ завжди", "Неважливо"],
                correctIndex: 0,
              },
            },
          ],
        },
        {
          slug: "king-pawn",
          titleUk: "Король і пішак",
          titleEn: "King and pawn",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "ch-eg1",
              type: "mcq",
              promptUk: "Опозиція в ендшпілі — це:",
              promptEn: "Opposition in the endgame is:",
              options: [
                "Королі один навпроти одного через клітинку",
                "Два ферзі",
                "Рокіровка",
                "Подвійний шах",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-eg2",
              type: "chess_lesson",
              promptUk: "Просування пішака",
              promptEn: "Pawn promotion",
              fen: "8/8/8/8/8/4k3/4P3/4K3 w - - 0 1",
              notesUk:
                "Підтримайте пішака королем. Не поспішайте — спочатку покращіть позицію короля.",
              notesEn:
                "Support the pawn with your king. Don't rush — improve the king first.",
              quiz: {
                q: "Що робити першим?",
                options: [
                  "Покращити позицію короля",
                  "Здатися",
                  "Рокіруватися",
                  "Ходити лише пішаком",
                ],
                correctIndex: 0,
              },
            },
          ],
        },
        {
          slug: "ladder-mate",
          titleUk: "Мат сходами",
          titleEn: "Ladder mate",
          baseXp: 24,
          difficulty: 3,
          exercises: [
            {
              id: "ch-eg3",
              type: "chess_puzzle",
              promptUk: "Мат двома турами (сходи)",
              fen: "4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1",
              solutionSans: ["Ra8#"],
              difficulty: 2,
            },
            {
              id: "ch-eg4",
              type: "mcq",
              promptUk: "Мат «сходами» роблять:",
              options: ["Дві тури (або тура+ферзь)", "Два коні", "Тільки пішаки", "Лише слони"],
              correctIndex: 0,
            },
          ],
        },
      ],
    },
    {
      slug: "tactics-boost",
      titleUk: "Тактика boost",
      titleEn: "Tactics boost",
      lessons: [
        {
          slug: "fork-basics",
          titleUk: "Вилка (fork)",
          titleEn: "Fork basics",
          baseXp: 22,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "ch-t1",
              type: "mcq",
              promptUk: "Вилка — це:",
              options: [
                "Одна фігура атакує дві цілі",
                "Лише рокіровка",
                "Здача партії",
                "Тільки пат",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-t2",
              type: "chess_puzzle",
              promptUk: "Кінь б'є з вилкою",
              fen: "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
              solutionSans: ["Ng5"],
              difficulty: 2,
            },
          ],
        },
        {
          slug: "pin-basics",
          titleUk: "Зв'язка (pin)",
          titleEn: "Pin basics",
          baseXp: 22,
          difficulty: 2,
          exercises: [
            {
              id: "ch-t3",
              type: "mcq",
              promptUk: "Зв'язка обмежує фігуру, бо:",
              options: [
                "За нею цінніша ціль (король/ферзь)",
                "Завжди незаконний хід",
                "Немає правил",
                "Тільки в ендшпілі",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-t4",
              type: "mcq",
              promptUk: "Абсолютна зв'язка — проти:",
              options: ["Короля", "Тільки пішака a2", "Порожньої клітини", "Рокіровки"],
              correctIndex: 0,
            },
          ],
        },
        {
          slug: "discovered-attack",
          titleUk: "Відкрите нападення",
          titleEn: "Discovered attack",
          baseXp: 24,
          difficulty: 3,
          exercises: [
            {
              id: "ch-t5",
              type: "mcq",
              promptUk: "Відкрите нападення виникає, коли:",
              options: [
                "Фігура йде з лінії, відкриваючи атаку іншої",
                "Робите лише 0-0",
                "З'їдаєте власну фігуру",
                "Пропускаєте хід",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-t6",
              type: "chess_lesson",
              promptUk: "Шукайте батареї тура/слон/ферзь",
              fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
              notesUk:
                "Розташуйте далекобійну фігуру за пішаком або конем — відхід відкриває удар.",
              quiz: {
                q: "Ключ до discovered attack?",
                options: ["Лінія + відхід", "Тільки кінь без лінії", "Лише ендшпіль", "Випадкові ходи"],
                correctIndex: 0,
              },
            },
          ],
        },
      ],
    },
    {
      slug: "tactics-practice-2",
      titleUk: "Тактика · практика 2",
      titleEn: "Tactics practice 2",
      lessons: [
        {
          slug: "mate-patterns-recap",
          titleUk: "Матові патерни",
          titleEn: "Mate patterns",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "ch-tp2-1",
              type: "mcq",
              promptUk: "Back-rank mate часто виникає коли:",
              promptEn: "Back-rank mate often happens when:",
              options: [
                "Король замкнений своїми пішаками на 1/8 горизонталі",
                "Немає ферзя в грі",
                "Лише в дебюті",
                "Після 0-0-0 завжди",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-tp2-2",
              type: "chess_puzzle",
              promptUk: "Мат у 1 (білі)",
              promptEn: "Mate in 1 (white)",
              fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
              solutionSans: ["Re8#"],
              difficulty: 2,
            },
          ],
        },
        {
          slug: "fork-drill",
          titleUk: "Вилка · drill",
          titleEn: "Fork drill",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "ch-tp2-3",
              type: "mcq",
              promptUk: "Кінська вилка б'є:",
              promptEn: "A knight fork hits:",
              options: [
                "Дві (і більше) фігури одним ходом",
                "Тільки пішака",
                "Лише короля суперника завжди",
                "Нічого",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-tp2-4",
              type: "chess_puzzle",
              promptUk: "Знайдіть вилку конем",
              promptEn: "Find the knight fork",
              fen: "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
              solutionSans: ["Nxe5"],
              difficulty: 2,
            },
          ],
        },
        {
          slug: "pin-drill",
          titleUk: "Зв'язка · drill",
          titleEn: "Pin drill",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "ch-tp2-5",
              type: "mcq",
              promptUk: "Абсолютна зв'язка — проти:",
              promptEn: "An absolute pin is against:",
              options: ["Короля", "Тільки тури a1", "Порожньої клітини", "Рокіровки"],
              correctIndex: 0,
            },
            {
              id: "ch-tp2-6",
              type: "chess_lesson",
              promptUk: "Шукайте лінії на короля",
              promptEn: "Look for lines toward the king",
              fen: "r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 2 3",
              notesUk: "Слон c4 тисне на f7 — класична тема італійської.",
              notesEn: "Bc4 pressures f7 — classic Italian theme.",
              quiz: {
                q: "Pin / pressure idea?",
                options: ["Line to king / weak point", "Random pawn push only", "Resign", "Ignore development"],
                correctIndex: 0,
              },
            },
          ],
        },
        {
          slug: "skewer-intro",
          titleUk: "Шпага (skewer)",
          titleEn: "Skewer intro",
          baseXp: 24,
          difficulty: 4,
          exercises: [
            {
              id: "ch-tp2-7",
              type: "mcq",
              promptUk: "Skewer — це:",
              promptEn: "A skewer is:",
              options: [
                "Удар по цінній фігурі, за якою стоїть менш цінна",
                "Лише рокіровка",
                "Хід пішаком e4",
                "Пат",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-tp2-8",
              type: "mcq",
              promptUk: "На відміну від pin, skewer:",
              promptEn: "Unlike a pin, a skewer:",
              options: [
                "Б'є спочатку ціннішу фігуру попереду",
                "Ніколи не працює з турою",
                "Можливий лише в ендшпілі без короля",
                "Заборонений правилами",
              ],
              correctIndex: 0,
            },
          ],
        },
        {
          slug: "tactics-mix-2",
          titleUk: "Мікс тактики 2",
          titleEn: "Tactics mix 2",
          baseXp: 24,
          difficulty: 4,
          exercises: [
            {
              id: "ch-tp2-9",
              type: "mcq",
              promptUk: "Подвійний удар може бути:",
              promptEn: "A double attack can be:",
              options: [
                "Вилкою, батареєю, нападом на дві цілі",
                "Лише взяттям en passant",
                "Тільки 0-0",
                "Ніколи в мідлгеймі",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-tp2-10",
              type: "chess_puzzle",
              promptUk: "Тактичний удар (білі)",
              promptEn: "Tactical shot (white)",
              fen: "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 5",
              solutionSans: ["Bxf7+"],
              difficulty: 3,
            },
          ],
        },
      ],
    },
  ],
};
