import type { CourseContent } from "./types.js";

export const chessContent: CourseContent = {
  slug: "chess",
  titleUk: "Шахи",
  titleEn: "Chess",
  descriptionUk: "Теорія, тактичні задачі та онлайн-партії.",
  descriptionEn: "Theory, puzzles, and live games with other players.",
  icon: "♟️",
  color: "#1B1B1B",
  units: [
    {
      slug: "rules",
      titleUk: "Правила",
      titleEn: "Правила",
      lessons: [
        {
          slug: "board-pieces",
          titleUk: "Дошка та фігури",
          titleEn: "Дошка та фігури",
          baseXp: 15,
          difficulty: 1,
          isFree: true,
          exercises: [
            {
              id: "ch-1-1",
              type: "chess_lesson",
              promptUk: "Початкова позиція",
              fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
              notesUk:
                "Білі ходять першими. Король — найважливіша фігура; мета гри — поставити мат королю суперника.",
              quiz: {
                q: "Хто ходить першим?",
                options: ["Чорні", "Білі", "Той, хто виграв жереб", "Будь-хто"],
                correctIndex: 1,
              },
            },
            {
              id: "ch-1-2",
              type: "mcq",
              promptUk: "Яка фігура ходить літерою «Г»?",
              options: ["Слон", "Тура", "Кінь", "Пішак"],
              correctIndex: 2,
            },
          ],
        },
        {
          slug: "king-check",
          titleUk: "Шах і мат",
          titleEn: "Шах і мат",
          baseXp: 18,
          difficulty: 1,
          isFree: true,
          exercises: [
            {
              id: "ch-2-1",
              type: "mcq",
              promptUk: "Що таке шах?",
              options: [
                "Атака на короля",
                "Взяття тури",
                "Рокіровка",
                "Хід пішаком на 2 клітинки",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-2-2",
              type: "chess_lesson",
              promptUk: "Мат — коли король під шахом і немає захисту",
              fen: "7k/5Q2/6K1/8/8/8/8/8 w - - 0 1",
              notesUk: "Ферзь на f7 захищений королем — чорний король у маті (після правильної постановки).",
              quiz: {
                q: "Мат означає:",
                options: [
                  "Гру закінчено, король під невідворотним шахом",
                  "Можна здатися",
                  "Нічия",
                  "Рокіровку",
                ],
                correctIndex: 0,
              },
            },
          ],
        },
        {
          slug: "special-moves",
          titleUk: "Спеціальні ходи",
          titleEn: "Спеціальні ходи",
          baseXp: 18,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "ch-3-1",
              type: "mcq",
              promptUk: "Рокіровка — це:",
              options: [
                "Хід королем і турою в одному ході",
                "Взяття на проході",
                "Перетворення пішака",
                "Подвійний шах",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-3-2",
              type: "mcq",
              promptUk: "Пішак, досягнувши 8-ї горизонталі:",
              options: ["Зникає", "Перетворюється", "Стоїть далі", "Стає королем"],
              correctIndex: 1,
            },
          ],
        },
      ],
    },
    {
      slug: "tactics",
      titleUk: "Тактика",
      titleEn: "Тактика",
      lessons: [
        {
          slug: "mate-in-1-a",
          titleUk: "Мат в 1: частина А",
          titleEn: "Мат в 1: частина А",
          baseXp: 20,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "ch-p1",
              type: "chess_puzzle",
              promptUk: "Знайдіть мат в 1 хід (білі)",
              fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
              solutionSans: ["Re8#"],
              difficulty: 1,
            },
            {
              id: "ch-p2",
              type: "chess_puzzle",
              promptUk: "Мат в 1: ферзь",
              fen: "r1bqkb1r/pppp1Qpp/2n2n2/4p3/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 0 1",
              solutionSans: ["Qxf7#"],
              difficulty: 1,
            },
          ],
        },
        {
          slug: "mate-in-1-b",
          titleUk: "Мат в 1: частина Б",
          titleEn: "Мат в 1: частина Б",
          baseXp: 20,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "ch-p3",
              type: "chess_puzzle",
              promptUk: "Мат турою",
              fen: "7k/6pp/8/8/8/8/8/R5K1 w - - 0 1",
              solutionSans: ["Ra8#"],
              difficulty: 1,
            },
            {
              id: "ch-p4",
              type: "chess_puzzle",
              promptUk: "Мат двома турами (класика)",
              fen: "4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1",
              solutionSans: ["Ra8#"],
              difficulty: 2,
            },
          ],
        },
        {
          slug: "forks",
          titleUk: "Вилки",
          titleEn: "Вилки",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "ch-p5",
              type: "chess_puzzle",
              promptUk: "Кінь бере з вилкою (проста позиція)",
              fen: "r1bqkb1r/pppp1ppp/2n2n2/4p1N1/2B1P3/8/PPPP1PPP/RNBQK2R w KQkq - 0 1",
              solutionSans: ["Nxf7"],
              difficulty: 2,
            },
            {
              id: "ch-p6",
              type: "mcq",
              promptUk: "Вилка — це:",
              options: [
                "Одна фігура атакує дві цілі",
                "Обмін ферзями",
                "Рокіровка під шахом",
                "Пат",
              ],
              correctIndex: 0,
            },
          ],
        },
        {
          slug: "pins-skewers",
          titleUk: "Зв'язки",
          titleEn: "Зв'язки",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "ch-p7",
              type: "mcq",
              promptUk: "Зв'язка (pin) — коли фігура:",
              options: [
                "Не може рухатись без відкриття ціннішої фігури",
                "З'їдає дві фігури",
                "Робить рокіровку",
                "Стає ферзем",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-p8",
              type: "chess_puzzle",
              promptUk: "Знайдіть сильний хід (шах)",
              fen: "r1bqk2r/pppp1ppp/2n2n2/2b1p1N1/2B1P3/3P4/PPP2PPP/RNBQK2R w KQkq - 0 1",
              solutionSans: ["Nxf7"],
              difficulty: 3,
            },
          ],
        },
        {
          slug: "more-puzzles",
          titleUk: "Ще задачі",
          titleEn: "Ще задачі",
          baseXp: 25,
          difficulty: 3,
          exercises: [
            {
              id: "ch-p9",
              type: "chess_puzzle",
              promptUk: "Мат ферзем",
              fen: "5k2/8/6K1/8/8/8/5Q2/8 w - - 0 1",
              solutionSans: ["Qf7#"],
              difficulty: 2,
            },
            {
              id: "ch-p10",
              type: "chess_puzzle",
              promptUk: "Мат в 1 (ладья + король)",
              fen: "7k/8/6K1/8/8/8/8/7R w - - 0 1",
              solutionSans: ["Rh8#"],
              difficulty: 1,
            },
          ],
        },
        {
          slug: "back-rank-mates",
          titleUk: "Мати на останній горизонталі",
          titleEn: "Мати на останній горизонталі",
          baseXp: 24,
          difficulty: 3,
          exercises: [
            {
              id: "ch-p11",
              type: "chess_puzzle",
              promptUk: "Back-rank мат",
              fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
              solutionSans: ["Re8#"],
              difficulty: 2,
            },
            {
              id: "ch-p12",
              type: "mcq",
              promptUk: "Back-rank mate — це:",
              options: [
                "Мат турою/ферзем на 8-й (1-й) горизонталі",
                "Мат конем",
                "Рокіровка",
                "Пат",
              ],
              correctIndex: 0,
            },
          ],
        },
        {
          slug: "opening-ideas",
          titleUk: "Ідеї дебюту",
          titleEn: "Ідеї дебюту",
          baseXp: 20,
          difficulty: 2,
          exercises: [
            {
              id: "ch-op1",
              type: "chess_lesson",
              promptUk: "Контроль центру",
              fen: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1",
              notesUk:
                "1.e4 займає центр і відкриває шляхи ферзю та слону. Мета дебюту: центр, розвиток, безпека короля.",
              quiz: {
                q: "Основна мета дебюту?",
                options: [
                  "Центр, розвиток, безпека короля",
                  "Тільки ходити пішаками",
                  "Здатися на 5-му ході",
                  "Не розвивати фігури",
                ],
                correctIndex: 0,
              },
            },
            {
              id: "ch-op2",
              type: "mcq",
              promptUk: "Чому важлива рокіровка?",
              options: [
                "Ховає короля й активує туру",
                "Дає зайвого ферзя",
                "З'їдає дві фігури",
                "Заборонена в бліці",
              ],
              correctIndex: 0,
            },
          ],
        },
      ],
    },
    {
      slug: "endgames-intro",
      titleUk: "Ендшпіль: вступ",
      titleEn: "Ендшпіль: вступ",
      lessons: [
        {
          slug: "king-pawn",
          titleUk: "Король і пішак",
          titleEn: "Король і пішак",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "ch-eg1",
              type: "mcq",
              promptUk: "Опозиція в ендшпілі — це:",
              options: [
                "Королі один навпроти одного через клітинку",
                "Два ферзі",
                "Рокіровка",
                "Подвійний шах",
              ],
              correctIndex: 0,
            },
            {
              id: "ch-eg2",
              type: "chess_lesson",
              promptUk: "Просування пішака",
              fen: "8/8/8/8/8/4k3/4P3/4K3 w - - 0 1",
              notesUk:
                "Підтримайте пішака королем. Не поспішайте — спочатку покращіть позицію короля.",
              quiz: {
                q: "Що робити першим?",
                options: [
                  "Покращити позицію короля",
                  "Здатися",
                  "Рокіруватися",
                  "Ходити лише пішаком",
                ],
                correctIndex: 0,
              },
            },
          ],
        },
        {
          slug: "ladder-mate",
          titleUk: "Мат сходами",
          titleEn: "Мат сходами",
          baseXp: 24,
          difficulty: 3,
          exercises: [
            {
              id: "ch-eg3",
              type: "chess_puzzle",
              promptUk: "Мат двома турами (сходи)",
              fen: "4k3/8/8/8/8/8/8/R3K2R w KQ - 0 1",
              solutionSans: ["Ra8#"],
              difficulty: 2,
            },
            {
              id: "ch-eg4",
              type: "mcq",
              promptUk: "Мат «сходами» роблять:",
              options: ["Дві тури (або тура+ферзь)", "Два коні", "Тільки пішаки", "Лише слони"],
              correctIndex: 0,
            },
          ],
        },
      ],
    },
  ],
};
