import type { CourseContent } from "./types.js";

export const englishContent: CourseContent = {
  slug: "english",
  titleUk: "Англійська",
  titleEn: "English",
  descriptionUk: "Вивчай англійську через короткі інтерактивні уроки.",
  descriptionEn: "Learn English through short interactive lessons.",
  icon: "🇬🇧",
  color: "#58CC02",
  units: [
    {
      slug: "basics-1",
      titleUk: "Основи 1",
      titleEn: "Basics 1",
      lessons: [
        {
          slug: "greetings",
          titleUk: "Привітання",
          titleEn: "Greetings",
          baseXp: 15,
          difficulty: 1,
          isFree: true,
          exercises: [
            {
              id: "en-1-1",
              type: "mcq",
              promptUk: "Як сказати «Привіт» англійською?",
              promptEn: "How do you say «Hello» in English?",
              options: ["Hello", "Goodbye", "Please", "Thanks"],
              correctIndex: 0,
              explanationUk: "Hello — найуніверсальніше привітання.",
              explanationEn: "Hello is the most universal greeting.",
            },
            {
              id: "en-1-2",
              type: "translate",
              promptUk: "Перекладіть українською",
              promptEn: "Translate into Ukrainian",
              source: "Good morning",
              accepted: ["доброго ранку", "добрий ранок"],
              direction: "en_uk",
            },
            {
              id: "en-1-3",
              type: "match",
              promptUk: "Зіставте слова",
              promptEn: "Match the words",
              pairs: [
                { left: "Hello", right: "Привіт" },
                { left: "Bye", right: "Бувай" },
                { left: "Thanks", right: "Дякую" },
              ],
            },
            {
              id: "en-1-4",
              type: "order_words",
              promptUk: "Складіть речення: «Мене звати Анна»",
              promptEn: "Build the sentence: «My name is Anna»",
              words: ["My", "name", "is", "Anna"],
              correct: ["My", "name", "is", "Anna"],
            },
          ],
        },
        {
          slug: "introductions",
          titleUk: "Знайомство",
          titleEn: "Introductions",
          baseXp: 15,
          difficulty: 1,
          isFree: true,
          exercises: [
            {
              id: "en-2-1",
              type: "mcq",
              promptUk: "What is your name? — відповідь:",
              options: ["I am fine", "My name is Oleg", "See you", "How are you"],
              correctIndex: 1,
            },
            {
              id: "en-2-2",
              type: "fill_blank",
              promptUk: "Заповніть пропуск",
              sentence: "Nice to ___ you.",
              accepted: ["meet"],
            },
            {
              id: "en-2-3",
              type: "translate",
              promptUk: "Перекладіть англійською",
              source: "Мені приємно познайомитися",
              accepted: ["nice to meet you", "pleased to meet you"],
              direction: "uk_en",
            },
          ],
        },
        {
          slug: "numbers",
          titleUk: "Числа 1–10",
          titleEn: "Числа 1–10",
          baseXp: 15,
          difficulty: 1,
          isFree: true,
          exercises: [
            {
              id: "en-3-1",
              type: "match",
              promptUk: "Числа",
              pairs: [
                { left: "one", right: "1" },
                { left: "five", right: "5" },
                { left: "ten", right: "10" },
                { left: "seven", right: "7" },
              ],
            },
            {
              id: "en-3-2",
              type: "mcq",
              promptUk: "Як буде 3?",
              options: ["tree", "three", "free", "there"],
              correctIndex: 1,
            },
            {
              id: "en-3-3",
              type: "order_words",
              promptUk: "I have two cats",
              words: ["I", "have", "two", "cats"],
              correct: ["I", "have", "two", "cats"],
            },
          ],
        },
        {
          slug: "food-basics",
          titleUk: "Їжа: основи",
          titleEn: "Їжа: основи",
          baseXp: 18,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "en-4-1",
              type: "mcq",
              promptUk: "apple — це:",
              options: ["яблуко", "банан", "хліб", "вода"],
              correctIndex: 0,
            },
            {
              id: "en-4-2",
              type: "translate",
              promptUk: "Перекладіть",
              source: "I like water",
              accepted: ["я люблю воду", "мені подобається вода"],
              direction: "en_uk",
            },
            {
              id: "en-4-3",
              type: "fill_blank",
              promptUk: "I ___ coffee.",
              sentence: "I ___ coffee.",
              accepted: ["drink", "like", "want"],
            },
          ],
        },
        {
          slug: "daily-phrases",
          titleUk: "Щоденні фрази",
          titleEn: "Щоденні фрази",
          baseXp: 18,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "en-5-1",
              type: "mcq",
              promptUk: "How are you?",
              options: ["I'm fine, thanks", "I'm a book", "Yes, please", "Two o'clock"],
              correctIndex: 0,
            },
            {
              id: "en-5-2",
              type: "order_words",
              promptUk: "Could you help me?",
              words: ["Could", "you", "help", "me?"],
              correct: ["Could", "you", "help", "me?"],
            },
            {
              id: "en-5-3",
              type: "translate",
              promptUk: "Перекладіть англійською",
              source: "Де туалет?",
              accepted: ["where is the bathroom", "where is the toilet", "where's the bathroom"],
              direction: "uk_en",
            },
          ],
        },
        {
          slug: "present-simple",
          titleUk: "Present Simple",
          titleEn: "Present Simple",
          baseXp: 20,
          difficulty: 2,
          exercises: [
            {
              id: "en-6-1",
              type: "mcq",
              promptUk: "She ___ to school every day.",
              options: ["go", "goes", "going", "gone"],
              correctIndex: 1,
              explanationUk: "3-тя особа однини: goes.",
            },
            {
              id: "en-6-2",
              type: "fill_blank",
              promptUk: "They ___ football on Sundays.",
              sentence: "They ___ football on Sundays.",
              accepted: ["play"],
            },
            {
              id: "en-6-3",
              type: "order_words",
              promptUk: "He does not like tea",
              words: ["He", "does", "not", "like", "tea"],
              correct: ["He", "does", "not", "like", "tea"],
            },
          ],
        },
        {
          slug: "colors-family",
          titleUk: "Кольори та сім'я",
          titleEn: "Кольори та сім'я",
          baseXp: 18,
          difficulty: 2,
          exercises: [
            {
              id: "en-7-1",
              type: "match",
              promptUk: "Кольори",
              pairs: [
                { left: "red", right: "червоний" },
                { left: "blue", right: "синій" },
                { left: "green", right: "зелений" },
              ],
            },
            {
              id: "en-7-2",
              type: "mcq",
              promptUk: "mother — це:",
              options: ["батько", "мати", "брат", "сестра"],
              correctIndex: 1,
            },
            {
              id: "en-7-3",
              type: "translate",
              promptUk: "Перекладіть",
              source: "My brother is tall",
              accepted: ["мій брат високий", "мій брат високий."],
              direction: "en_uk",
            },
          ],
        },
        {
          slug: "questions",
          titleUk: "Питання",
          titleEn: "Питання",
          baseXp: 20,
          difficulty: 3,
          exercises: [
            {
              id: "en-8-1",
              type: "mcq",
              promptUk: "___ is this? — This is a pen.",
              options: ["Who", "What", "Where", "When"],
              correctIndex: 1,
            },
            {
              id: "en-8-2",
              type: "order_words",
              promptUk: "Where do you live?",
              words: ["Where", "do", "you", "live?"],
              correct: ["Where", "do", "you", "live?"],
            },
            {
              id: "en-8-3",
              type: "fill_blank",
              promptUk: "___ old are you?",
              sentence: "___ old are you?",
              accepted: ["how"],
            },
          ],
        },
      ],
    },
    {
      slug: "basics-2",
      titleUk: "Основи 2",
      titleEn: "Основи 2",
      lessons: [
        {
          slug: "time",
          titleUk: "Час",
          titleEn: "Час",
          baseXp: 20,
          difficulty: 2,
          exercises: [
            {
              id: "en-9-1",
              type: "mcq",
              promptUk: "It's half past two =",
              options: ["2:30", "2:00", "3:30", "12:30"],
              correctIndex: 0,
            },
            {
              id: "en-9-2",
              type: "translate",
              promptUk: "Перекладіть",
              source: "What time is it?",
              accepted: ["котра година", "котра година?", "яка година", "яка година?"],
              direction: "en_uk",
            },
          ],
        },
        {
          slug: "places",
          titleUk: "Місця",
          titleEn: "Місця",
          baseXp: 20,
          difficulty: 2,
          exercises: [
            {
              id: "en-10-1",
              type: "match",
              promptUk: "Місця в місті",
              pairs: [
                { left: "school", right: "школа" },
                { left: "shop", right: "магазин" },
                { left: "park", right: "парк" },
              ],
            },
            {
              id: "en-10-2",
              type: "fill_blank",
              promptUk: "I go ___ the park.",
              sentence: "I go ___ the park.",
              accepted: ["to"],
            },
          ],
        },
        {
          slug: "past-simple-intro",
          titleUk: "Past Simple (вступ)",
          titleEn: "Past Simple (вступ)",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "en-11-1",
              type: "mcq",
              promptUk: "Yesterday I ___ home.",
              options: ["go", "went", "goes", "going"],
              correctIndex: 1,
            },
            {
              id: "en-11-2",
              type: "order_words",
              promptUk: "She watched a film",
              words: ["She", "watched", "a", "film"],
              correct: ["She", "watched", "a", "film"],
            },
          ],
        },
      ],
    },
    {
      slug: "travel",
      titleUk: "Подорожі",
      titleEn: "Подорожі",
      lessons: [
        {
          slug: "airport",
          titleUk: "В аеропорту",
          titleEn: "В аеропорту",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "en-12-1",
              type: "mcq",
              promptUk: "boarding pass — це:",
              options: ["посадковий талон", "паспорт", "валіза", "квиток на автобус"],
              correctIndex: 0,
            },
            {
              id: "en-12-2",
              type: "translate",
              promptUk: "Перекладіть англійською",
              source: "Де вихід на посадку?",
              accepted: ["where is the gate", "where's the gate", "where is my gate"],
              direction: "uk_en",
            },
          ],
        },
        {
          slug: "hotel",
          titleUk: "У готелі",
          titleEn: "У готелі",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "en-13-1",
              type: "order_words",
              promptUk: "I have a reservation",
              words: ["I", "have", "a", "reservation"],
              correct: ["I", "have", "a", "reservation"],
            },
            {
              id: "en-13-2",
              type: "mcq",
              promptUk: "I'd like a room for two nights.",
              options: [
                "Я хочу кімнату на дві ночі",
                "Я хочу сніданок",
                "Де пляж?",
                "Скільки коштує таксі?",
              ],
              correctIndex: 0,
            },
          ],
        },
        {
          slug: "restaurant",
          titleUk: "У ресторані",
          titleEn: "У ресторані",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "en-14-1",
              type: "match",
              promptUk: "Меню",
              pairs: [
                { left: "menu", right: "меню" },
                { left: "bill", right: "рахунок" },
                { left: "waiter", right: "офіціант" },
              ],
            },
            {
              id: "en-14-2",
              type: "translate",
              promptUk: "Перекладіть англійською",
              source: "Можна меню, будь ласка?",
              accepted: ["can i have the menu please", "can i see the menu please", "menu please"],
              direction: "uk_en",
            },
            {
              id: "en-14-3",
              type: "mcq",
              promptUk: "I'm allergic to nuts.",
              options: [
                "У мене алергія на горіхи",
                "Я люблю горіхи",
                "Рахунок, будь ласка",
                "Я вегетаріанець",
              ],
              correctIndex: 0,
            },
          ],
        },
        {
          slug: "shopping",
          titleUk: "Покупки",
          titleEn: "Покупки",
          baseXp: 20,
          difficulty: 2,
          exercises: [
            {
              id: "en-15-1",
              type: "fill_blank",
              promptUk: "How much ___ it cost?",
              sentence: "How much ___ it cost?",
              accepted: ["does"],
            },
            {
              id: "en-15-2",
              type: "order_words",
              promptUk: "Can I try this on?",
              words: ["Can", "I", "try", "this", "on?"],
              correct: ["Can", "I", "try", "this", "on?"],
            },
            {
              id: "en-15-3",
              type: "mcq",
              promptUk: "size — це:",
              options: ["розмір", "ціна", "колір", "магазин"],
              correctIndex: 0,
            },
          ],
        },
      ],
    },
    {
      slug: "work-life",
      titleUk: "Робота та побут",
      titleEn: "Робота та побут",
      lessons: [
        {
          slug: "office",
          titleUk: "В офісі",
          titleEn: "В офісі",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "en-16-1",
              type: "match",
              promptUk: "Офіс",
              pairs: [
                { left: "meeting", right: "зустріч" },
                { left: "deadline", right: "дедлайн" },
                { left: "colleague", right: "колега" },
              ],
            },
            {
              id: "en-16-2",
              type: "mcq",
              promptUk: "I'll send you an email.",
              options: [
                "Я надішлю вам email",
                "Я подзвоню завтра",
                "Зустріч скасована",
                "Я в відпустці",
              ],
              correctIndex: 0,
            },
          ],
        },
        {
          slug: "present-continuous",
          titleUk: "Present Continuous",
          titleEn: "Present Continuous",
          baseXp: 24,
          difficulty: 3,
          exercises: [
            {
              id: "en-17-1",
              type: "mcq",
              promptUk: "She ___ right now.",
              options: ["works", "is working", "worked", "work"],
              correctIndex: 1,
            },
            {
              id: "en-17-2",
              type: "order_words",
              promptUk: "They are watching a film",
              words: ["They", "are", "watching", "a", "film"],
              correct: ["They", "are", "watching", "a", "film"],
            },
            {
              id: "en-17-3",
              type: "fill_blank",
              promptUk: "I ___ learning English.",
              sentence: "I ___ learning English.",
              accepted: ["am"],
            },
          ],
        },
        {
          slug: "future-plans",
          titleUk: "Плани на майбутнє",
          titleEn: "Плани на майбутнє",
          baseXp: 24,
          difficulty: 3,
          exercises: [
            {
              id: "en-18-1",
              type: "mcq",
              promptUk: "I ___ visit Lviv next week.",
              options: ["am going to", "goes to", "going", "gone"],
              correctIndex: 0,
            },
            {
              id: "en-18-2",
              type: "translate",
              promptUk: "Перекладіть",
              source: "What are you going to do?",
              accepted: ["що ти збираєшся робити", "що ви збираєтесь робити", "що ти будеш робити"],
              direction: "en_uk",
            },
          ],
        },
        {
          slug: "opinions",
          titleUk: "Думки та згода",
          titleEn: "Думки та згода",
          baseXp: 22,
          difficulty: 3,
          exercises: [
            {
              id: "en-19-1",
              type: "match",
              promptUk: "Фрази згоди",
              pairs: [
                { left: "I agree", right: "Я згоден" },
                { left: "I disagree", right: "Я не згоден" },
                { left: "Maybe", right: "Можливо" },
              ],
            },
            {
              id: "en-19-2",
              type: "order_words",
              promptUk: "In my opinion it is great",
              words: ["In", "my", "opinion", "it", "is", "great"],
              correct: ["In", "my", "opinion", "it", "is", "great"],
            },
          ],
        },
        {
          slug: "review-basics",
          titleUk: "Повторення основ",
          titleEn: "Повторення основ",
          baseXp: 25,
          difficulty: 3,
          exercises: [
            {
              id: "en-20-1",
              type: "mcq",
              promptUk: "He ___ coffee every morning.",
              options: ["drink", "drinks", "drinking", "drank"],
              correctIndex: 1,
            },
            {
              id: "en-20-2",
              type: "fill_blank",
              promptUk: "___ you like tea?",
              sentence: "___ you like tea?",
              accepted: ["do"],
            },
            {
              id: "en-20-3",
              type: "translate",
              promptUk: "Перекладіть англійською",
              source: "Я вивчаю англійську щодня",
              accepted: [
                "i study english every day",
                "i learn english every day",
                "i'm learning english every day",
                "i am learning english every day",
              ],
              direction: "uk_en",
            },
          ],
        },
        {
          slug: "travel-phrases",
          titleUk: "Подорожі: фрази",
          titleEn: "Travel phrases",
          baseXp: 22,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "en-21-1",
              type: "mcq",
              promptUk: "Where is the station?",
              promptEn: "Choose the natural question:",
              options: [
                "Where is the station?",
                "Where the station is?",
                "Station where?",
                "Is where station?",
              ],
              correctIndex: 0,
            },
            {
              id: "en-21-2",
              type: "translate",
              promptUk: "Перекладіть: Скільки це коштує?",
              source: "Скільки це коштує?",
              accepted: ["how much is it", "how much does it cost", "what's the price"],
              direction: "uk_en",
            },
            {
              id: "en-21-3",
              type: "match",
              promptUk: "Travel vocab",
              pairs: [
                { left: "ticket", right: "квиток" },
                { left: "passport", right: "паспорт" },
                { left: "luggage", right: "багаж" },
              ],
            },
          ],
        },
        {
          slug: "email-soft-skills",
          titleUk: "Email soft skills",
          titleEn: "Email soft skills",
          baseXp: 24,
          difficulty: 3,
          exercises: [
            {
              id: "en-22-1",
              type: "mcq",
              promptUk: "Polite opener:",
              options: [
                "I hope this email finds you well.",
                "Answer me now.",
                "You must fix this.",
                "Hey do it",
              ],
              correctIndex: 0,
            },
            {
              id: "en-22-2",
              type: "order_words",
              promptUk: "Could you please send the report?",
              words: ["Could", "you", "please", "send", "the", "report?"],
              correct: ["Could", "you", "please", "send", "the", "report?"],
            },
            {
              id: "en-22-3",
              type: "fill_blank",
              promptUk: "Looking forward ___ hearing from you.",
              sentence: "Looking forward ___ hearing from you.",
              accepted: ["to"],
            },
          ],
        },
        {
          slug: "idioms-boost",
          titleUk: "Ідіоми boost",
          titleEn: "Idioms boost",
          baseXp: 26,
          difficulty: 4,
          exercises: [
            {
              id: "en-23-1",
              type: "mcq",
              promptUk: "Break the ice means:",
              options: [
                "Start a friendly conversation",
                "Destroy a fridge",
                "Fail an exam",
                "Run fast",
              ],
              correctIndex: 0,
            },
            {
              id: "en-23-2",
              type: "mcq",
              promptUk: "Hit the books:",
              options: ["Study hard", "Throw books", "Buy books only", "Sleep"],
              correctIndex: 0,
            },
            {
              id: "en-23-3",
              type: "translate",
              promptUk: "Перекладіть: practice makes perfect",
              source: "practice makes perfect",
              accepted: [
                "практика робить досконалим",
                "практика веде до досконалості",
                "повторення — мати навчання",
              ],
              direction: "en_uk",
            },
          ],
        },
      ],
    },
    {
      slug: "conversation",
      titleUk: "Розмова · small talk",
      titleEn: "Conversation · small talk",
      lessons: [
        {
          slug: "small-talk-weather",
          titleUk: "Small talk: погода",
          titleEn: "Small talk: weather",
          baseXp: 18,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "en-conv-1",
              type: "mcq",
              promptUk: "How's the weather? — типова відповідь:",
              promptEn: "How's the weather? — a typical reply:",
              options: ["It's sunny today", "I am weather", "Yes book", "Go home forever"],
              correctIndex: 0,
              explanationUk: "Описуємо погоду: sunny, rainy, cloudy…",
              explanationEn: "Describe weather: sunny, rainy, cloudy…",
            },
            {
              id: "en-conv-2",
              type: "order_words",
              promptUk: "Складіть: Nice day, isn't it?",
              promptEn: "Order: Nice day, isn't it?",
              words: ["it?", "Nice", "isn't", "day,"],
              correct: ["Nice", "day,", "isn't", "it?"],
            },
            {
              id: "en-conv-3",
              type: "match",
              promptUk: "Зіставте small talk",
              promptEn: "Match small-talk pairs",
              pairs: [
                { left: "How are you?", right: "I'm fine, thanks" },
                { left: "See you later", right: "Bye for now" },
                { left: "Long time no see", right: "We haven't met in a while" },
              ],
            },
          ],
        },
        {
          slug: "small-talk-weekend",
          titleUk: "Вихідні та плани",
          titleEn: "Weekend plans",
          baseXp: 18,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "en-conv-4",
              type: "translate",
              promptUk: "Перекладіть: What are you up to this weekend?",
              promptEn: "Translate: What are you up to this weekend?",
              source: "What are you up to this weekend?",
              accepted: [
                "що ти робиш на цих вихідних",
                "які в тебе плани на вихідні",
                "чим займаєшся на вихідних",
              ],
              direction: "en_uk",
            },
            {
              id: "en-conv-5",
              type: "fill_blank",
              promptUk: "I'm looking ___ to the party.",
              promptEn: "I'm looking ___ to the party.",
              sentence: "I'm looking ___ to the party.",
              accepted: ["forward"],
            },
            {
              id: "en-conv-6",
              type: "mcq",
              promptUk: "Catch up later means:",
              promptEn: "Catch up later means:",
              options: [
                "Talk / meet later",
                "Run faster now",
                "Delete the chat",
                "Sleep all day",
              ],
              correctIndex: 0,
              explanationUk: "Catch up — наздогнати зв'язок / зустрітись поговорити.",
              explanationEn: "Catch up — reconnect or meet to talk later.",
            },
          ],
        },
        {
          slug: "polite-requests",
          titleUk: "Ввічливі прохання",
          titleEn: "Polite requests",
          baseXp: 20,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "en-conv-7",
              type: "mcq",
              promptUk: "Найввічливіше:",
              promptEn: "Most polite:",
              options: [
                "Could you help me, please?",
                "Help now!",
                "You must help",
                "Do it",
              ],
              correctIndex: 0,
            },
            {
              id: "en-conv-8",
              type: "order_words",
              promptUk: "Would you mind opening the window?",
              promptEn: "Order: Would you mind opening the window?",
              words: ["mind", "Would", "opening", "you", "the", "window?"],
              correct: ["Would", "you", "mind", "opening", "the", "window?"],
            },
            {
              id: "en-conv-9",
              type: "fill_blank",
              promptUk: "___ you pass me the salt?",
              promptEn: "___ you pass me the salt?",
              sentence: "___ you pass me the salt?",
              accepted: ["Could", "Would", "Can"],
            },
          ],
        },
        {
          slug: "agree-disagree",
          titleUk: "Погодитись / заперечити",
          titleEn: "Agree & disagree",
          baseXp: 20,
          difficulty: 3,
          exercises: [
            {
              id: "en-conv-10",
              type: "match",
              promptUk: "Зіставте реакції",
              promptEn: "Match reactions",
              pairs: [
                { left: "I agree", right: "Same here" },
                { left: "I'm not sure", right: "Maybe" },
                { left: "I disagree", right: "I see it differently" },
              ],
            },
            {
              id: "en-conv-11",
              type: "mcq",
              promptUk: "That's a good point means:",
              promptEn: "That's a good point means:",
              options: [
                "You made a valid argument",
                "The pencil is sharp",
                "Leave the room",
                "Score is zero",
              ],
              correctIndex: 0,
              explanationUk: "Визнаємо слушність думки співрозмовника.",
              explanationEn: "You acknowledge a valid argument.",
            },
            {
              id: "en-conv-12",
              type: "translate",
              promptUk: "Перекладіть: I see what you mean",
              promptEn: "Translate: I see what you mean",
              source: "I see what you mean",
              accepted: [
                "я розумію що ти маєш на увазі",
                "розумію про що ти",
                "бачу що ти маєш на увазі",
              ],
              direction: "en_uk",
            },
          ],
        },
      ],
    },
    {
      slug: "meetings-phone",
      titleUk: "Дзвінки та мітинги",
      titleEn: "Calls & meetings",
      lessons: [
        {
          slug: "phone-basics",
          titleUk: "Телефон: базові фрази",
          titleEn: "Phone basics",
          baseXp: 18,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "en-ph-1",
              type: "mcq",
              promptUk: "How to answer a work call politely?",
              promptEn: "How to answer a work call politely?",
              options: [
                "Hello, this is Alex speaking",
                "Who this?",
                "What?",
                "Call later forever",
              ],
              correctIndex: 0,
              explanationUk: "Представтесь: This is … speaking.",
              explanationEn: "Introduce yourself: This is … speaking.",
            },
            {
              id: "en-ph-2",
              type: "match",
              promptUk: "Зіставте фрази",
              promptEn: "Match phrases",
              pairs: [
                { left: "Can I take a message?", right: "Можу передати повідомлення?" },
                { left: "You're breaking up", right: "Зв'язок поганий" },
                { left: "I'll call you back", right: "Передзвоню" },
              ],
            },
            {
              id: "en-ph-3",
              type: "fill_blank",
              promptUk: "Could you speak a bit ___? I can't hear you.",
              promptEn: "Could you speak a bit ___? I can't hear you.",
              sentence: "Could you speak a bit ___? I can't hear you.",
              accepted: ["louder", "slower", "clearer"],
            },
          ],
        },
        {
          slug: "meeting-open",
          titleUk: "Початок мітингу",
          titleEn: "Opening a meeting",
          baseXp: 20,
          difficulty: 2,
          isFree: true,
          exercises: [
            {
              id: "en-mt-1",
              type: "order_words",
              promptUk: "Let's get started, shall we?",
              promptEn: "Order: Let's get started, shall we?",
              words: ["started,", "Let's", "shall", "get", "we?"],
              correct: ["Let's", "get", "started,", "shall", "we?"],
            },
            {
              id: "en-mt-2",
              type: "mcq",
              promptUk: "Agenda means:",
              promptEn: "Agenda means:",
              options: [
                "List of topics for the meeting",
                "Only a calendar app icon",
                "Password",
                "Coffee break forever",
              ],
              correctIndex: 0,
            },
            {
              id: "en-mt-3",
              type: "translate",
              promptUk: "Перекладіть: Thanks for joining",
              promptEn: "Translate: Thanks for joining",
              source: "Thanks for joining",
              accepted: [
                "дякую що приєднались",
                "дякую за участь",
                "дякую що долучились",
              ],
              direction: "en_uk",
            },
          ],
        },
        {
          slug: "meeting-clarify",
          titleUk: "Уточнення на мітингу",
          titleEn: "Clarifying in meetings",
          baseXp: 20,
          difficulty: 3,
          exercises: [
            {
              id: "en-mt-4",
              type: "mcq",
              promptUk: "Could you expand on that? means:",
              promptEn: "Could you expand on that? means:",
              options: [
                "Please give more detail",
                "Stop talking",
                "Share your screen only",
                "End the call",
              ],
              correctIndex: 0,
            },
            {
              id: "en-mt-5",
              type: "fill_blank",
              promptUk: "Just to ___ — the deadline is Friday, right?",
              promptEn: "Just to ___ — the deadline is Friday, right?",
              sentence: "Just to ___ — the deadline is Friday, right?",
              accepted: ["clarify", "confirm", "check"],
            },
            {
              id: "en-mt-6",
              type: "match",
              promptUk: "Зіставте",
              promptEn: "Match",
              pairs: [
                { left: "Action item", right: "Завдання після мітингу" },
                { left: "Takeaway", right: "Головний висновок" },
                { left: "Follow up", right: "Продовжити / перевірити пізніше" },
              ],
            },
          ],
        },
        {
          slug: "wrap-up-call",
          titleUk: "Закриття дзвінка",
          titleEn: "Wrapping up a call",
          baseXp: 18,
          difficulty: 2,
          exercises: [
            {
              id: "en-mt-7",
              type: "mcq",
              promptUk: "Polite goodbye on a work call:",
              promptEn: "Polite goodbye on a work call:",
              options: [
                "Thanks, talk soon. Bye!",
                "Whatever",
                "Hang up now",
                "Silence only",
              ],
              correctIndex: 0,
            },
            {
              id: "en-mt-8",
              type: "order_words",
              promptUk: "I'll send the notes after the call",
              promptEn: "Order: I'll send the notes after the call",
              words: ["send", "I'll", "the", "notes", "after", "the", "call"],
              correct: ["I'll", "send", "the", "notes", "after", "the", "call"],
            },
          ],
        },
      ],
    },
  ],
};
