export type FlashcardSeed = {
  front: string;
  back: string;
  hint?: string;
  tags?: string[];
};

export type DeckSeed = {
  slug: string;
  titleUk: string;
  titleEn: string;
  descriptionUk: string;
  descriptionEn: string;
  courseSlug: string;
  cards: FlashcardSeed[];
};

export const FLASHCARD_DECKS: DeckSeed[] = [
  {
    slug: "programming-basics",
    titleUk: "Програмування: основи",
    titleEn: "Programming: basics",
    descriptionUk: "HTML/CSS/JS ключові терміни",
    descriptionEn: "HTML/CSS/JS key terms",
    courseSlug: "programming",
    cards: [
      { front: "<div>", back: "блочний контейнер / block container", tags: ["html"] },
      { front: "href", back: "URL посилання / link URL", tags: ["html"] },
      { front: "flexbox", back: "1D layout (row/column)", tags: ["css"] },
      { front: "const", back: "непереприсвоювана змінна", tags: ["js"] },
      { front: "useState", back: "React hook локального стану", tags: ["react"] },
      { front: "express()", back: "створити Express app", tags: ["express"] },
      { front: "SELECT *", back: "усі колонки таблиці", tags: ["sql"] },
      { front: "unit test", back: "тест модуля/функції", tags: ["qa"] },
      { front: "middleware", back: "шар обробки req у Express", tags: ["express"] },
      { front: "props", back: "вхідні дані компонента React", tags: ["react"] },
      { front: "map()", back: "новий масив з перетворених елементів", tags: ["js"] },
      { front: "filter()", back: "новий масив за умовою", tags: ["js"] },
      { front: "express.json()", back: "парсить JSON body у req.body", tags: ["express"] },
      { front: "NULL", back: "невідоме / відсутнє значення в SQL", tags: ["sql"] },
      { front: "COALESCE", back: "перше ненульове значення", tags: ["sql"] },
    ],
  },

  {
    slug: "english-basics",
    titleUk: "Англійська: основи",
    titleEn: "English: basics",
    descriptionUk: "Базові слова та фрази (SRS)",
    descriptionEn: "Core words and phrases (SRS)",
    courseSlug: "english",
    cards: [
      { front: "Hello", back: "Привіт", tags: ["greetings"] },
      { front: "Good morning", back: "Доброго ранку", tags: ["greetings"] },
      { front: "Goodbye", back: "Бувай / До побачення", tags: ["greetings"] },
      { front: "Thank you", back: "Дякую", tags: ["polite"] },
      { front: "Please", back: "Будь ласка", tags: ["polite"] },
      { front: "Sorry", back: "Вибач / Вибачте", tags: ["polite"] },
      { front: "Yes", back: "Так", tags: ["basics"] },
      { front: "No", back: "Ні", tags: ["basics"] },
      { front: "My name is…", back: "Мене звати…", tags: ["intro"] },
      { front: "Nice to meet you", back: "Приємно познайомитись", tags: ["intro"] },
      { front: "How are you?", back: "Як справи?", tags: ["intro"] },
      { front: "I am fine", back: "У мене все добре", tags: ["intro"] },
      { front: "Water", back: "Вода", tags: ["nouns"] },
      { front: "Food", back: "Їжа", tags: ["nouns"] },
      { front: "Friend", back: "Друг / Подруга", tags: ["nouns"] },
      { front: "School", back: "Школа", tags: ["nouns"] },
      { front: "Book", back: "Книга", tags: ["nouns"] },
      { front: "Teacher", back: "Вчитель / Вчителька", tags: ["nouns"] },
      { front: "I have a cat", back: "У мене є кіт", tags: ["sentences"] },
      { front: "Where is the station?", back: "Де станція?", tags: ["travel"] },
      { front: "Could you speak louder?", back: "Можете говорити голосніше?", tags: ["phone"] },
      { front: "I'll call you back", back: "Передзвоню", tags: ["phone"] },
      { front: "Let's get started", back: "Давайте почнемо", tags: ["meetings"] },
      { front: "Just to clarify…", back: "Щоб уточнити…", tags: ["meetings"] },
      { front: "Action item", back: "Завдання / follow-up після мітингу", tags: ["meetings"] },
      { front: "Thanks for joining", back: "Дякую, що приєднались", tags: ["meetings"] },
    ],
  },
  {
    slug: "english-meetings",
    titleUk: "Англійська: мітинги",
    titleEn: "English: meetings",
    descriptionUk: "Фрази для дзвінків і мітингів",
    descriptionEn: "Phrases for calls and meetings",
    courseSlug: "english",
    cards: [
      { front: "You're breaking up", back: "Зв'язок рветься / погано чути", tags: ["phone"] },
      { front: "Can I take a message?", back: "Можу передати повідомлення?", tags: ["phone"] },
      { front: "What's on the agenda?", back: "Що в порядку денному?", tags: ["meetings"] },
      { front: "Could you expand on that?", back: "Можете розгорнути детальніше?", tags: ["meetings"] },
      { front: "I see your point", back: "Розумію вашу думку", tags: ["meetings"] },
      { front: "Let's wrap up", back: "Давайте завершимо", tags: ["meetings"] },
      { front: "I'll send the notes", back: "Надішлю нотатки", tags: ["meetings"] },
      { front: "Talk soon", back: "На зв'язку / поговоримо скоро", tags: ["phone"] },
    ],
  },
  {
    slug: "chess-terms",
    titleUk: "Шахи: терміни",
    titleEn: "Chess: terms",
    descriptionUk: "Основна шахова лексика",
    descriptionEn: "Core chess vocabulary",
    courseSlug: "chess",
    cards: [
      { front: "King", back: "Король", tags: ["pieces"] },
      { front: "Queen", back: "Ферзь", tags: ["pieces"] },
      { front: "Rook", back: "Тура", tags: ["pieces"] },
      { front: "Bishop", back: "Слон", tags: ["pieces"] },
      { front: "Knight", back: "Кінь", tags: ["pieces"] },
      { front: "Pawn", back: "Пішак", tags: ["pieces"] },
      { front: "Check", back: "Шах", tags: ["rules"] },
      { front: "Checkmate", back: "Мат", tags: ["rules"] },
      { front: "Stalemate", back: "Пат", tags: ["rules"] },
      { front: "Castling", back: "Рокіровка", tags: ["rules"] },
      { front: "En passant", back: "Взяття на проході", tags: ["rules"] },
      { front: "Fork", back: "Вилка", tags: ["tactics"] },
      { front: "Pin", back: "Зв'язка", tags: ["tactics"] },
      { front: "Skewer", back: "Лінійний удар", tags: ["tactics"] },
      { front: "Opening", back: "Дебют", tags: ["phases"] },
    ],
  },
  {
    slug: "logic-patterns",
    titleUk: "Логіка: підказки",
    titleEn: "Logic: tips",
    descriptionUk: "Корисні патерни для задач",
    descriptionEn: "Useful problem-solving patterns",
    courseSlug: "logic",
    cards: [
      { front: "Sequence", back: "Послідовність", hint: "знайди крок / rule", tags: ["vocab"] },
      { front: "Pattern", back: "Закономірність", tags: ["vocab"] },
      { front: "Odd one out", back: "Зайве / виключення", tags: ["types"] },
      { front: "Analogy A:B :: C:?", back: "Пропорція / аналогія", tags: ["types"] },
      { front: "Eliminate options", back: "Відсікай неможливі відповіді", tags: ["strategy"] },
      { front: "Work backwards", back: "Йди від відповіді назад", tags: ["strategy"] },
      { front: "Draw it", back: "Намалюй / схематизуй", tags: ["strategy"] },
      { front: "Check extremes", back: "Перевір крайні випадки", tags: ["strategy"] },
    ],
  },
  {
    slug: "miltech-embedded",
    titleUk: "MilTech: ключові терміни",
    titleEn: "MilTech: key terms",
    descriptionUk: "Embedded C++ · RTOS · link · mission",
    descriptionEn: "Embedded C++ · RTOS · link · mission",
    courseSlug: "embedded_cpp",
    cards: [
      { front: "MCU", back: "CPU + memory + peripherals for real-time", tags: ["hardware"] },
      { front: "RAII", back: "Resource lifetime tied to object ctor/dtor", tags: ["cpp"] },
      { front: "unique_ptr", back: "Single-owner smart pointer", tags: ["cpp"] },
      { front: "CRC", back: "Checksum to detect transmission errors", tags: ["net"] },
      { front: "UDP", back: "Connectionless datagrams, low latency", tags: ["net"] },
      { front: "TCP", back: "Reliable ordered stream", tags: ["net"] },
      { front: "FreeRTOS", back: "Tasks, queues, scheduling on MCU", tags: ["rtos"] },
      { front: "xTaskCreate", back: "Create a FreeRTOS task", tags: ["rtos"] },
      { front: "Watchdog", back: "Reset if software hangs", tags: ["safety"] },
      { front: "IRQ", back: "Hardware interrupt for async events", tags: ["hardware"] },
      { front: "UART", back: "Async serial point-to-point bus", tags: ["bus"] },
      { front: "I2C", back: "Multi-device 2-wire bus", tags: ["bus"] },
      { front: "SPI", back: "Fast master/slave serial bus", tags: ["bus"] },
      { front: "MAVLink", back: "Messaging protocol for vehicles/GCS", tags: ["uav"] },
      { front: "SITL", back: "Software-in-the-loop simulation", tags: ["uav"] },
      { front: "HITL", back: "Hardware-in-the-loop testing", tags: ["uav"] },
      { front: "GCS", back: "Ground control station (operator UI)", tags: ["uav"] },
      { front: "SBC", back: "Companion computer for high-level work", tags: ["uav"] },
      { front: "PID", back: "Control: Proportional + Integral + Derivative", tags: ["control"] },
      { front: "QoS (ROS 2)", back: "Reliability / history tradeoffs on topics", tags: ["ros"] },
      { front: "Topic", back: "Pub/sub channel in ROS 2", tags: ["ros"] },
      { front: "Failsafe", back: "Safe mode on link/sensor fault", tags: ["safety"] },
      { front: "BIT", back: "Built-in test / health self-check", tags: ["safety"] },
      { front: "Bandwidth budget", back: "Plan bytes/s across message classes", tags: ["link"] },
      { front: "Geofence", back: "Safety keep-in/out virtual boundary", tags: ["mission"] },
      { front: "State machine", back: "Explicit modes + legal transitions", tags: ["mission"] },
      { front: "Ring buffer", back: "Circular queue for streaming samples", tags: ["data"] },
      { front: "Endianness", back: "Byte order (little vs big)", tags: ["memory"] },
      { front: "Event loop", back: "poll → update → act cycle", tags: ["cpp"] },
      { front: "ASan", back: "AddressSanitizer finds memory bugs", tags: ["toolchain"] },
    ],
  },
];
