/** Auto-generated skill-course promptEn map. Source: scripts/gen-skill-prompt-en.mjs */
export const SKILL_PROMPT_EN_BY_ID: Record<string, string> = {
  "en-2-1": "What is your name? — choose the answer:",
  "en-2-2": "Fill in the blank",
  "en-2-3": "Translate into English",
  "en-3-1": "Numbers",
  "en-3-2": "How do you say 3 in English?",
  "en-3-3": "Put the words in order: I have two cats",
  "en-4-1": "apple means:",
  "en-4-2": "Translate",
  "en-4-3": "I ___ coffee.",
  "en-5-1": "How are you? — choose the best reply",
  "en-5-2": "Put the words in order: Could you help me?",
  "en-5-3": "Translate into English",
  "en-6-1": "She ___ to school every day.",
  "en-6-2": "They ___ football on Sundays.",
  "en-6-3": "Put the words in order: He does not like tea",
  "en-7-1": "Colors",
  "en-7-2": "mother means:",
  "en-7-3": "Translate",
  "en-8-1": "___ is this? — This is a pen.",
  "en-8-2": "Put the words in order: Where do you live?",
  "en-8-3": "___ old are you?",
  "en-9-1": "It's half past two means:",
  "en-9-2": "Translate",
  "en-10-1": "Places in the city",
  "en-10-2": "I go ___ the park.",
  "en-11-1": "Yesterday I ___ home.",
  "en-11-2": "Put the words in order: She watched a film",
  "en-12-1": "boarding pass means:",
  "en-12-2": "Translate into English",
  "en-13-1": "Put the words in order: I have a reservation",
  "en-13-2": "I'd like a room for two nights. — choose the meaning",
  "en-14-1": "Menu",
  "en-14-2": "Translate into English",
  "en-14-3": "I'm allergic to nuts. — choose the meaning",
  "en-15-1": "How much ___ it cost?",
  "en-15-2": "Put the words in order: Can I try this on?",
  "en-15-3": "size means:",
  "en-16-1": "Office",
  "en-16-2": "I'll send you an email. — choose the meaning",
  "en-17-1": "She ___ right now.",
  "en-17-2": "Put the words in order: They are watching a film",
  "en-17-3": "I ___ learning English.",
  "en-18-1": "I ___ visit Lviv next week.",
  "en-18-2": "Translate",
  "en-19-1": "Agreement phrases",
  "en-19-2": "Put the words in order: In my opinion it is great",
  "en-20-1": "He ___ coffee every morning.",
  "en-20-2": "___ you like tea?",
  "en-20-3": "Translate into English",
  "ch-1-1": "Starting position",
  "ch-1-2": "Which piece moves in an L-shape?",
  "ch-2-1": "What is check?",
  "ch-2-2": "Checkmate — the king is in check and has no escape",
  "ch-3-1": "Castling is:",
  "ch-3-2": "A pawn that reaches the 8th rank:",
  "ch-p1": "Find mate in 1 (White to move)",
  "ch-p2": "Mate in 1: queen",
  "ch-p3": "Mate with a rook",
  "ch-p4": "Mate with two rooks (classic)",
  "ch-p5": "Knight fork (simple position)",
  "ch-p6": "A fork is:",
  "ch-p7": "A pin is when a piece:",
  "ch-p8": "Find a strong move (check)",
  "ch-p9": "Mate with the queen",
  "ch-p10": "Mate in 1 (rook + king)",
  "ch-p11": "Back-rank mate",
  "ch-p12": "Back-rank mate is:",
  "ch-op1": "Control of the center",
  "ch-op2": "Why is castling important?",
  "ch-eg1": "Opposition in the endgame is:",
  "ch-eg2": "Pawn promotion",
  "ch-eg3": "Mate with two rooks (ladder)",
  "ch-eg4": "A ladder mate is delivered by:",
  "sr-1-1": "In speed reading, RSVP means:",
  "sr-1-2": "Practice RSVP (slow)",
  "sr-2-1": "Subvocalization is:",
  "sr-2-2": "RSVP medium pace",
  "sr-3-1": "Chunking helps you:",
  "sr-3-2": "Faster RSVP",
  "sr-4-1": "Read and answer",
  "sr-5-1": "Warm-up",
  "sr-5-2": "Text about habits",
  "sr-6-1": "The goal of peripheral vision training:",
  "sr-6-2": "Pace 320 wpm",
  "sr-7-1": "Science and focus",
  "sr-8-1": "400 wpm — short text",
  "sr-8-2": "The best strategy:",
  "sr-9-1": "About chess and learning",
  "sr-10-1": "The key to progress in speed reading:",
  "sr-10-2": "Final RSVP",
  "sr-11-1": "Skimming is:",
  "sr-11-2": "Skimming an article",
  "sr-12-1": "Scanning a text is useful to:",
  "sr-12-2": "RSVP 360",
  "sr-13-1": "Sleep and memory",
  "sr-14-1": "380 wpm",
  "sr-14-2": "Final rule:",
  "lg-1": "2, 4, 6, 8, ?",
  "lg-2": "1, 2, 4, 8, ?",
  "lg-3": "3, 6, 9, 12, ?",
  "lg-4": "5, 10, 20, 40, ?",
  "lg-5": "1, 1, 2, 3, 5, ?",
  "lg-6": "10, 9, 7, 4, ?",
  "lg-7": "2, 3, 5, 7, 11, ?",
  "lg-8": "100, 50, 25, ?",
  "lg-9": "A, C, E, G, ?",
  "lg-10": "Z, Y, X, W, ?",
  "lg-11": "Square, circle, square, circle, ?",
  "lg-12": "▲ ▲ ■ ▲ ▲ ■ ▲ ▲ ?",
  "lg-13": "In the matrix [1 2 / 3 ?]: if the pattern is +2 down, what replaces ?",
  "lg-14": "2 4 / 3 6 / 4 ?",
  "lg-15": "Odd one out: cat, dog, table, rabbit?",
  "lg-16": "Odd one out: apple, pear, carrot, plum?",
  "lg-17": "Odd one out: square, circle, triangle, cube?",
  "lg-18": "Odd one out: Monday, March, Wednesday, Friday?",
  "lg-19": "Day → night, as hot → ?",
  "lg-20": "Bird → nest, as bee → ?",
  "lg-21": "Book → read, as song → ?",
  "lg-22": "Doctor → hospital, as teacher → ?",
  "lg-23": "All fish breathe underwater. Salmon is a fish. Therefore:",
  "lg-24": "If it rains, the ground is wet. The ground is wet. Is it raining?",
  "lg-25": "A is taller than B. B is taller than C. Who is shortest?",
  "lg-26": "A train is faster than a bus. A bus is faster than a bike. Slowest?",
  "lg-27": "7, 14, 28, 56, ?",
  "lg-28": "Odd one out: pen, pencil, notebook, apple?",
  "lg-29": "Table → furniture, as rose → ?",
  "lg-30": "1, 4, 9, 16, ?",
  "lg-31": "If 2+3=10, 3+4=21, 4+5=36, then 5+6=?",
  "lg-32": "Continue: 1, 2, 6, 24, ?",
  "lg-33": "Three sisters have 3, 5 and 7 apples. How many in total?",
  "lg-34": "A clock shows 3:15. Approximate angle between hands?",
  "lg-35": "2, 6, 12, 20, 30, ?",
  "lg-36": "All squares are rhombi. Some rhombi are not squares. Are all rhombi squares?",
  "lg-37": "8, 6, 9, 5, 10, 4, ?",
  "lg-38": "Calculate: 3+5*2=?",
  "lg-39": "1, 3, 7, 15, 31, ?",
  "lg-40": "Odd one out: violin, guitar, drum, hammer?",
  "lg-41": "Book → pages, as house → ?",
  "lg-42": "9, 16, 25, 36, ?",
  "lg-43": "All athletes train. Oleh is an athlete. Therefore:",
  "lg-44": "No cat is a dog. Barsik is a cat. Therefore Barsik:",
  "lg-45": "2, 5, 11, 23, ?",
  "lg-46": "4, 9, 19, 39, ?",
  "lg-47": "If A > B and B > C, then A ? C",
  "lg-48": "1/2, 1/4, 1/8, ?",
  "lg-49": "Three kids ate 2, 3 and 5 candies. How many total?",
  "lg-50": "12, 11, 9, 6, 2, ?",
};
