import type { CourseContent, Exercise, LessonContent, UnitContent } from "./types.js";

function lesson(
  slug: string,
  titleUk: string,
  titleEn: string,
  difficulty: number,
  isFree: boolean,
  exercises: Exercise[],
  extra?: { isExam?: boolean; passThreshold?: number; baseXp?: number },
): LessonContent {
  return {
    slug,
    titleUk,
    titleEn,
    baseXp: extra?.baseXp ?? 12 + difficulty * 3,
    difficulty,
    isFree,
    isExam: extra?.isExam,
    passThreshold: extra?.passThreshold,
    exercises,
  };
}

function unit(
  slug: string,
  titleUk: string,
  titleEn: string,
  lessons: LessonContent[],
): UnitContent {
  return { slug, titleUk, titleEn, lessons };
}

function exam(
  slug: string,
  titleUk: string,
  titleEn: string,
  difficulty: number,
  exercises: Exercise[],
): LessonContent {
  return lesson(slug, titleUk, titleEn, difficulty, false, exercises, {
    isExam: true,
    passThreshold: 0.7,
    baseXp: 28,
  });
}

/* ——— basics ——— */
const basics = unit("basics", "Основи TS", "TS basics", [
  lesson(
    "tsc-what-is-ts",
    "Що таке TypeScript",
    "What is TypeScript",
    1,
    true,
    [
      {
        id: "tsc-b1",
        type: "mcq",
        promptUk: "TypeScript — це:",
        promptEn: "TypeScript is:",
        options: [
          "окремий runtime замість JS",
          "надмножина JS зі статичними типами",
          "CSS-препроцесор",
          "база даних",
        ],
        correctIndex: 1,
      },
      {
        id: "tsc-b2",
        type: "mcq",
        promptUk: "TS компілюється переважно в:",
        promptEn: "TS primarily compiles to:",
        options: ["Python", "JavaScript", "WASM only", "SQL"],
        correctIndex: 1,
      },
      {
        id: "tsc-b3",
        type: "code_fill",
        promptUk: "Анотація типу number",
        promptEn: "Number type annotation",
        language: "ts",
        code: "let age: ___ = 18;",
        accepted: ["number"],
        caseSensitive: true,
      },
    ],
  ),
  lesson(
    "tsc-primitives",
    "Примітиви",
    "Primitives",
    1,
    true,
    [
      {
        id: "tsc-b4",
        type: "code_output",
        promptUk: "Який тип у `typeof true`?",
        promptEn: "What is `typeof true`?",
        language: "ts",
        code: "typeof true",
        options: ['"boolean"', '"bool"', '"number"', '"object"'],
        correctIndex: 0,
      },
      {
        id: "tsc-b5",
        type: "code_fill",
        promptUk: "Рядок",
        promptEn: "String type",
        language: "ts",
        code: "const name: ___ = 'Ada';",
        accepted: ["string"],
        caseSensitive: true,
      },
      {
        id: "tsc-b6",
        type: "mcq",
        promptUk: "`null` і `undefined` у strict TS:",
        promptEn: "`null` and `undefined` in strict TS:",
        options: [
          "завжди взаємозамінні",
          "окремі типи, часто в union",
          "лише number",
          "заборонені назавжди",
        ],
        correctIndex: 1,
      },
    ],
  ),
  lesson(
    "tsc-annotations",
    "Анотації та inference",
    "Annotations & inference",
    2,
    false,
    [
      {
        id: "tsc-b7",
        type: "mcq",
        promptUk: "Type inference означає:",
        promptEn: "Type inference means:",
        options: [
          "типи лише в runtime",
          "компілятор виводить тип із значення",
          "відсутність типів",
          "тільки any",
        ],
        correctIndex: 1,
      },
      {
        id: "tsc-b8",
        type: "code_read",
        promptUk: "Чи скомпілюється (strict)?",
        promptEn: "Does this compile (strict)?",
        language: "ts",
        code: "const n: number = '1';",
        options: ["Так", "Ні — string ↛ number", "Лише з any", "Так, coercion"],
        correctIndex: 1,
      },
      {
        id: "tsc-b9",
        type: "code_fill",
        promptUk: "Boolean flag",
        promptEn: "Boolean flag",
        language: "ts",
        code: "let ready: ___ = false;",
        accepted: ["boolean"],
        caseSensitive: true,
      },
    ],
  ),
  exam("tsc-basics-exam", "Контрольна: основи", "Exam: basics", 2, [
    {
      id: "tsc-be1",
      type: "mcq",
      promptUk: "Головна користь TypeScript:",
      promptEn: "Main benefit of TypeScript:",
      options: ["швидший DOM", "статична перевірка типів", "без npm", "заміна HTML"],
      correctIndex: 1,
    },
    {
      id: "tsc-be2",
      type: "code_fill",
      promptUk: "Тип числа",
      promptEn: "Number type",
      language: "ts",
      code: "let x: ___ = 0;",
      accepted: ["number"],
      caseSensitive: true,
    },
    {
      id: "tsc-be3",
      type: "code_read",
      promptUk: "Помилка в коді?",
      promptEn: "Error in code?",
      language: "ts",
      code: "const ok: boolean = 1;",
      options: ["OK", "number ↛ boolean", "syntax only", "runtime always"],
      correctIndex: 1,
    },
    {
      id: "tsc-be4",
      type: "mcq",
      promptUk: "tsc перетворює TS на:",
      promptEn: "tsc turns TS into:",
      options: ["Java", "JavaScript", "Kotlin", "Ruby"],
      correctIndex: 1,
    },
    {
      id: "tsc-be5",
      type: "code_fill",
      promptUk: "Рядок",
      promptEn: "String",
      language: "ts",
      code: "type Name = ___;",
      accepted: ["string"],
      caseSensitive: true,
    },
  ]),
]);

/* ——— objects ——— */
const objects = unit("objects", "Об'єкти й масиви", "Objects & arrays", [
  lesson(
    "tsc-objects",
    "Object types",
    "Object types",
    2,
    false,
    [
      {
        id: "tsc-o1",
        type: "code_order",
        promptUk: "Тип об'єкта user",
        promptEn: "User object type",
        language: "ts",
        lines: ["}", "type User = {", "id: number;"],
        correct: ["type User = {", "id: number;", "}"],
      },
      {
        id: "tsc-o2",
        type: "code_fill",
        promptUk: "Optional поле",
        promptEn: "Optional field",
        language: "ts",
        code: "type P = { name___: string };",
        accepted: ["?"],
        caseSensitive: true,
      },
    ],
  ),
  lesson(
    "tsc-arrays-tuples",
    "Arrays & tuples",
    "Arrays & tuples",
    2,
    false,
    [
      {
        id: "tsc-o3",
        type: "code_fill",
        promptUk: "Масив чисел",
        promptEn: "Number array",
        language: "ts",
        code: "const xs: ___[] = [1, 2];",
        accepted: ["number"],
        caseSensitive: true,
      },
      {
        id: "tsc-o4",
        type: "mcq",
        promptUk: "Tuple у TS — це:",
        promptEn: "A tuple in TS is:",
        options: [
          "лише string[]",
          "фіксована довжина + типи позицій",
          "клас",
          "async функція",
        ],
        correctIndex: 1,
      },
      {
        id: "tsc-o5",
        type: "code_read",
        promptUk: "Тип tuple?",
        promptEn: "Tuple type?",
        language: "ts",
        code: "const p: [string, number] = ['a', 1];",
        options: ["invalid", "OK", "needs any", "only in JS"],
        correctIndex: 1,
      },
    ],
  ),
  lesson(
    "tsc-enums",
    "Enums (intro)",
    "Enums (intro)",
    2,
    false,
    [
      {
        id: "tsc-o6",
        type: "mcq",
        promptUk: "enum у TS часто замінюють на:",
        promptEn: "enums are often replaced by:",
        options: ["union string literals", "CSS vars", "SQL ENUM only", "void"],
        correctIndex: 0,
      },
      {
        id: "tsc-o7",
        type: "code_fill",
        promptUk: "Union literals",
        promptEn: "Union literals",
        language: "ts",
        code: "type Role = 'admin' ___ 'user';",
        accepted: ["|"],
        caseSensitive: true,
      },
    ],
  ),
  exam("tsc-objects-exam", "Контрольна: objects", "Exam: objects", 2, [
    {
      id: "tsc-oe1",
      type: "code_fill",
      promptUk: "Масив рядків",
      promptEn: "String array",
      language: "ts",
      code: "const tags: ___[] = [];",
      accepted: ["string"],
      caseSensitive: true,
    },
    {
      id: "tsc-oe2",
      type: "mcq",
      promptUk: "Optional property:",
      promptEn: "Optional property:",
      options: ["name!", "name?", "name*", "name#"],
      correctIndex: 1,
    },
    {
      id: "tsc-oe3",
      type: "code_read",
      promptUk: "Чи OK tuple?",
      promptEn: "Tuple OK?",
      language: "ts",
      code: "const t: [number, number] = [1, 2, 3];",
      options: ["OK always", "Error length", "Only any", "Runtime only"],
      correctIndex: 1,
    },
    {
      id: "tsc-oe4",
      type: "mcq",
      promptUk: "type Point = { x: number; y: number } — це:",
      promptEn: "type Point = { x: number; y: number } is:",
      options: ["class instance", "object type alias", "enum", "module"],
      correctIndex: 1,
    },
  ]),
]);

/* ——— interfaces ——— */
const interfaces = unit("interfaces", "Interface & type", "Interface & type", [
  lesson(
    "tsc-interface-basics",
    "interface basics",
    "interface basics",
    2,
    false,
    [
      {
        id: "tsc-i1",
        type: "code_order",
        promptUk: "interface User",
        promptEn: "interface User",
        language: "ts",
        lines: ["}", "interface User {", "email: string;"],
        correct: ["interface User {", "email: string;", "}"],
      },
      {
        id: "tsc-i2",
        type: "mcq",
        promptUk: "interface vs type alias — спільне:",
        promptEn: "interface vs type alias — shared:",
        options: [
          "обидва описують форми об'єктів",
          "лише interface для unions",
          "type не існує",
          "лише runtime",
        ],
        correctIndex: 0,
      },
    ],
  ),
  lesson(
    "tsc-extends",
    "extends / intersection",
    "extends / intersection",
    3,
    false,
    [
      {
        id: "tsc-i3",
        type: "code_fill",
        promptUk: "extends",
        promptEn: "extends",
        language: "ts",
        code: "interface Admin ___ User { role: 'admin' }",
        accepted: ["extends"],
        caseSensitive: true,
      },
      {
        id: "tsc-i4",
        type: "code_fill",
        promptUk: "Intersection",
        promptEn: "Intersection",
        language: "ts",
        code: "type Both = A ___ B;",
        accepted: ["&"],
        caseSensitive: true,
      },
      {
        id: "tsc-i5",
        type: "mcq",
        promptUk: "Declaration merging більше характерне для:",
        promptEn: "Declaration merging is more typical of:",
        options: ["interface", "type alias", "const", "enum only"],
        correctIndex: 0,
      },
    ],
  ),
  exam("tsc-interfaces-exam", "Контрольна: interfaces", "Exam: interfaces", 3, [
    {
      id: "tsc-ie1",
      type: "mcq",
      promptUk: "interface описує:",
      promptEn: "interface describes:",
      options: ["лише CSS", "форму значення/об'єкта", "SQL table only", "git branch"],
      correctIndex: 1,
    },
    {
      id: "tsc-ie2",
      type: "code_fill",
      promptUk: "extends keyword",
      promptEn: "extends keyword",
      language: "ts",
      code: "interface B ___ A {}",
      accepted: ["extends"],
      caseSensitive: true,
    },
    {
      id: "tsc-ie3",
      type: "code_fill",
      promptUk: "Intersection of types",
      promptEn: "Intersection of types",
      language: "ts",
      code: "type C = A ___ B;",
      accepted: ["&"],
      caseSensitive: true,
    },
    {
      id: "tsc-ie4",
      type: "mcq",
      promptUk: "Optional в interface:",
      promptEn: "Optional in interface:",
      options: ["prop?", "prop!", "prop~", "prop#"],
      correctIndex: 0,
    },
  ]),
]);

/* ——— functions ——— */
const functions = unit("functions", "Функції", "Functions", [
  lesson(
    "tsc-fn-types",
    "Типи параметрів і return",
    "Param & return types",
    2,
    false,
    [
      {
        id: "tsc-f1",
        type: "code_fill",
        promptUk: "Return type",
        promptEn: "Return type",
        language: "ts",
        code: "function add(a: number, b: number): ___ { return a + b; }",
        accepted: ["number"],
        caseSensitive: true,
      },
      {
        id: "tsc-f2",
        type: "mcq",
        promptUk: "void означає:",
        promptEn: "void means:",
        options: ["будь-який тип", "функція нічого корисного не повертає", "null only", "never"],
        correctIndex: 1,
      },
    ],
  ),
  lesson(
    "tsc-fn-optional",
    "Optional / default params",
    "Optional / default params",
    2,
    false,
    [
      {
        id: "tsc-f3",
        type: "code_fill",
        promptUk: "Optional param",
        promptEn: "Optional param",
        language: "ts",
        code: "function greet(name___: string) {}",
        accepted: ["?"],
        caseSensitive: true,
      },
      {
        id: "tsc-f4",
        type: "code_read",
        promptUk: "Що з default?",
        promptEn: "About default?",
        language: "ts",
        code: "function f(n = 1) { return n; }",
        options: ["n: any only", "n inferred as number", "error always", "n is string"],
        correctIndex: 1,
      },
    ],
  ),
  exam("tsc-functions-exam", "Контрольна: functions", "Exam: functions", 2, [
    {
      id: "tsc-fe1",
      type: "code_fill",
      promptUk: "Return string",
      promptEn: "Return string",
      language: "ts",
      code: "function id(s: string): ___ { return s; }",
      accepted: ["string"],
      caseSensitive: true,
    },
    {
      id: "tsc-fe2",
      type: "mcq",
      promptUk: "void vs never:",
      promptEn: "void vs never:",
      options: [
        "те саме",
        "never — функція не завершується нормально",
        "void = number",
        "never = string",
      ],
      correctIndex: 1,
    },
    {
      id: "tsc-fe3",
      type: "code_fill",
      promptUk: "Optional arg",
      promptEn: "Optional arg",
      language: "ts",
      code: "function log(msg___: string) {}",
      accepted: ["?"],
      caseSensitive: true,
    },
    {
      id: "tsc-fe4",
      type: "mcq",
      promptUk: "Тип функції (call signature) можна описати через:",
      promptEn: "Function type can be written as:",
      options: ["(a: number) => number", "only class", "only enum", "CSS"],
      correctIndex: 0,
    },
  ]),
]);

/* ——— generics ——— */
const generics = unit("generics", "Generics", "Generics", [
  lesson(
    "tsc-generics-fn",
    "Generic functions",
    "Generic functions",
    3,
    false,
    [
      {
        id: "tsc-g1",
        type: "code_read",
        promptUk: "Що повертає identity?",
        promptEn: "What does identity return?",
        language: "ts",
        code: "function id<T>(x: T): T { return x; }",
        options: ["завжди string", "той самий тип T", "void", "any only"],
        correctIndex: 1,
      },
      {
        id: "tsc-g2",
        type: "code_fill",
        promptUk: "Generic param name",
        promptEn: "Generic param name",
        language: "ts",
        code: "function first<___>(arr: T[]): T | undefined { return arr[0]; }",
        accepted: ["T"],
        caseSensitive: true,
      },
    ],
  ),
  lesson(
    "tsc-generics-constraints",
    "Constraints",
    "Constraints",
    3,
    false,
    [
      {
        id: "tsc-g3",
        type: "code_fill",
        promptUk: "extends constraint",
        promptEn: "extends constraint",
        language: "ts",
        code: "function len<T ___ { length: number }>(x: T) { return x.length; }",
        accepted: ["extends"],
        caseSensitive: true,
      },
      {
        id: "tsc-g4",
        type: "mcq",
        promptUk: "Constraints обмежують:",
        promptEn: "Constraints limit:",
        options: ["runtime CPU", "які типи можна підставити в T", "лише CSS", "git"],
        correctIndex: 1,
      },
    ],
  ),
  exam("tsc-generics-exam", "Контрольна: generics", "Exam: generics", 3, [
    {
      id: "tsc-ge1",
      type: "mcq",
      promptUk: "Generics дають:",
      promptEn: "Generics provide:",
      options: ["параметризовані типи", "лише DOM", "SQL joins", "CSS grid"],
      correctIndex: 0,
    },
    {
      id: "tsc-ge2",
      type: "code_fill",
      promptUk: "Constraint keyword",
      promptEn: "Constraint keyword",
      language: "ts",
      code: "function f<T ___ object>(x: T) { return x; }",
      accepted: ["extends"],
      caseSensitive: true,
    },
    {
      id: "tsc-ge3",
      type: "code_read",
      promptUk: "Тип id(42)?",
      promptEn: "Type of id(42)?",
      language: "ts",
      code: "function id<T>(x: T): T { return x; }\nid(42);",
      options: ["string", "number", "any", "void"],
      correctIndex: 1,
    },
    {
      id: "tsc-ge4",
      type: "mcq",
      promptUk: "T[] у generic означає:",
      promptEn: "T[] in generics means:",
      options: ["масив елементів типу T", "tuple always", "only string", "null"],
      correctIndex: 0,
    },
  ]),
]);

/* ——— narrowing ——— */
const narrowing = unit("narrowing", "Narrowing", "Narrowing", [
  lesson(
    "tsc-unions",
    "Unions",
    "Unions",
    2,
    false,
    [
      {
        id: "tsc-n1",
        type: "code_fill",
        promptUk: "Union",
        promptEn: "Union",
        language: "ts",
        code: "type Id = string ___ number;",
        accepted: ["|"],
        caseSensitive: true,
      },
      {
        id: "tsc-n2",
        type: "mcq",
        promptUk: "typeof x === 'string' у TS:",
        promptEn: "typeof x === 'string' in TS:",
        options: ["видаляє x", "звужує тип (narrowing)", "SQL", "disable strict"],
        correctIndex: 1,
      },
    ],
  ),
  lesson(
    "tsc-guards",
    "Type guards",
    "Type guards",
    3,
    false,
    [
      {
        id: "tsc-n3",
        type: "mcq",
        promptUk: "in operator guard:",
        promptEn: "in operator guard:",
        options: [
          "перевіряє наявність властивості для narrowing",
          "лише CSS",
          "видаляє тип",
          "тільки runtime crash",
        ],
        correctIndex: 0,
      },
      {
        id: "tsc-n4",
        type: "code_read",
        promptUk: "Discriminated union?",
        promptEn: "Discriminated union?",
        language: "ts",
        code: "type S = { kind: 'a'; n: number } | { kind: 'b'; s: string };",
        options: ["invalid", "OK pattern", "needs any", "only class"],
        correctIndex: 1,
      },
      {
        id: "tsc-n5",
        type: "mcq",
        promptUk: "Після if (s.kind === 'a') у discriminated union:",
        promptEn: "After if (s.kind === 'a') in a discriminated union:",
        options: [
          "s звужується до варіанту a",
          "s стає any",
          "s видаляється",
          "помилка завжди",
        ],
        correctIndex: 0,
      },
    ],
  ),
  exam("tsc-narrowing-exam", "Контрольна: narrowing", "Exam: narrowing", 3, [
    {
      id: "tsc-ne1",
      type: "code_fill",
      promptUk: "Union operator",
      promptEn: "Union operator",
      language: "ts",
      code: "type U = A ___ B;",
      accepted: ["|"],
      caseSensitive: true,
    },
    {
      id: "tsc-ne2",
      type: "mcq",
      promptUk: "Narrowing — це:",
      promptEn: "Narrowing is:",
      options: [
        "звуження union до точнішого типу",
        "видалення файлів",
        "мініфікація",
        "git rebase",
      ],
      correctIndex: 0,
    },
    {
      id: "tsc-ne3",
      type: "mcq",
      promptUk: "Discriminant field типово:",
      promptEn: "Discriminant field is typically:",
      options: ["kind / type literal", "any", "Function", "CSS class"],
      correctIndex: 0,
    },
    {
      id: "tsc-ne4",
      type: "code_read",
      promptUk: "Після typeof",
      promptEn: "After typeof",
      language: "ts",
      code: "function f(x: string | number) {\n  if (typeof x === 'string') return x.toUpperCase();\n  return x + 1;\n}",
      options: ["error always", "OK", "needs any", "only JS"],
      correctIndex: 1,
    },
  ]),
]);

/* ——— utilities ——— */
const utilities = unit("utilities", "Utility types", "Utility types", [
  lesson(
    "tsc-partial-pick",
    "Partial & Pick",
    "Partial & Pick",
    3,
    false,
    [
      {
        id: "tsc-u1",
        type: "mcq",
        promptUk: "Partial<T> робить:",
        promptEn: "Partial<T> makes:",
        options: [
          "усі поля required",
          "усі поля optional",
          "T = never",
          "видаляє T",
        ],
        correctIndex: 1,
      },
      {
        id: "tsc-u2",
        type: "code_fill",
        promptUk: "Pick name from User",
        promptEn: "Pick name from User",
        language: "ts",
        code: "type N = ___<User, 'name'>;",
        accepted: ["Pick"],
        caseSensitive: true,
      },
    ],
  ),
  lesson(
    "tsc-omit-record",
    "Omit & Record",
    "Omit & Record",
    3,
    false,
    [
      {
        id: "tsc-u3",
        type: "code_fill",
        promptUk: "Omit password",
        promptEn: "Omit password",
        language: "ts",
        code: "type Public = ___<User, 'password'>;",
        accepted: ["Omit"],
        caseSensitive: true,
      },
      {
        id: "tsc-u4",
        type: "mcq",
        promptUk: "Record<K, V> — це:",
        promptEn: "Record<K, V> is:",
        options: [
          "об'єкт з ключами K і значеннями V",
          "масив V",
          "Promise",
          "CSS map",
        ],
        correctIndex: 0,
      },
    ],
  ),
  exam("tsc-utilities-exam", "Контрольна: utilities", "Exam: utilities", 3, [
    {
      id: "tsc-ue1",
      type: "mcq",
      promptUk: "Partial<T>:",
      promptEn: "Partial<T>:",
      options: ["optional fields", "required fields", "readonly only", "never"],
      correctIndex: 0,
    },
    {
      id: "tsc-ue2",
      type: "code_fill",
      promptUk: "Pick utility",
      promptEn: "Pick utility",
      language: "ts",
      code: "type X = ___<T, 'a' | 'b'>;",
      accepted: ["Pick"],
      caseSensitive: true,
    },
    {
      id: "tsc-ue3",
      type: "code_fill",
      promptUk: "Omit utility",
      promptEn: "Omit utility",
      language: "ts",
      code: "type Y = ___<T, 'secret'>;",
      accepted: ["Omit"],
      caseSensitive: true,
    },
    {
      id: "tsc-ue4",
      type: "mcq",
      promptUk: "Record<string, number>:",
      promptEn: "Record<string, number>:",
      options: ["map-like object type", "tuple", "enum", "class only"],
      correctIndex: 0,
    },
  ]),
]);

/* ——— modules ——— */
const modules = unit("modules", "Modules & tsconfig", "Modules & tsconfig", [
  lesson(
    "tsc-import-export",
    "import / export",
    "import / export",
    2,
    false,
    [
      {
        id: "tsc-m1",
        type: "code_fill",
        promptUk: "Named export",
        promptEn: "Named export",
        language: "ts",
        code: "___ function add(a: number, b: number) { return a + b; }",
        accepted: ["export"],
        caseSensitive: true,
      },
      {
        id: "tsc-m2",
        type: "mcq",
        promptUk: "import type { User } — означає:",
        promptEn: "import type { User } means:",
        options: [
          "імпорт лише типу (erase at emit)",
          "runtime class only",
          "CSS import",
          "SQL",
        ],
        correctIndex: 0,
      },
    ],
  ),
  lesson(
    "tsc-tsconfig",
    "tsconfig basics",
    "tsconfig basics",
    2,
    false,
    [
      {
        id: "tsc-m3",
        type: "mcq",
        promptUk: "strict: true вмикає:",
        promptEn: "strict: true enables:",
        options: [
          "набір суворих перевірок типів",
          "тільки prettier",
          "вимкнення types",
          "SQL mode",
        ],
        correctIndex: 0,
      },
      {
        id: "tsc-m4",
        type: "mcq",
        promptUk: "target у tsconfig:",
        promptEn: "target in tsconfig:",
        options: [
          "версія JS на виході",
          "лише npm registry",
          "port сервера",
          "CSS target",
        ],
        correctIndex: 0,
      },
    ],
  ),
  exam("tsc-modules-exam", "Контрольна: modules", "Exam: modules", 2, [
    {
      id: "tsc-me1",
      type: "code_fill",
      promptUk: "export keyword",
      promptEn: "export keyword",
      language: "ts",
      code: "___ const PI = 3.14;",
      accepted: ["export"],
      caseSensitive: true,
    },
    {
      id: "tsc-me2",
      type: "mcq",
      promptUk: "strict mode:",
      promptEn: "strict mode:",
      options: ["stricter type checks", "faster CSS", "no modules", "disables tsc"],
      correctIndex: 0,
    },
    {
      id: "tsc-me3",
      type: "mcq",
      promptUk: "import type:",
      promptEn: "import type:",
      options: ["type-only import", "loads CSS", "SQL", "runtime polyfill always"],
      correctIndex: 0,
    },
    {
      id: "tsc-me4",
      type: "mcq",
      promptUk: "module: \"ESNext\" впливає на:",
      promptEn: "module: \"ESNext\" affects:",
      options: ["emit module system", "only fonts", "Postgres", "Redis"],
      correctIndex: 0,
    },
  ]),
]);

/* ——— capstone ——— */
const capstone = unit("capstone", "Capstone", "Capstone", [
  lesson(
    "tsc-capstone-util",
    "Mini: typed util",
    "Mini: typed util",
    3,
    false,
    [
      {
        id: "tsc-c1",
        type: "code_project",
        promptUk:
          "TS: interface User { id: number; name: string }, function greet(u: User): string. README згадує interface.",
        promptEn:
          "TS: interface User { id: number; name: string }, function greet(u: User): string. README mentions interface.",
        files: [
          {
            id: "ts",
            name: "greet.ts",
            language: "typescript",
            starter: `// TODO: interface User + greet(u: User): string
export {};
`,
          },
          {
            id: "md",
            name: "README.md",
            language: "markdown",
            starter: `# Types
<!-- TODO: mention interface -->
`,
          },
        ],
        checks: [
          {
            fileId: "ts",
            contains: [
              "interface User",
              "id:",
              "name:",
              "function greet",
              "User",
              "string",
            ],
          },
          { fileId: "md", contains: ["interface"] },
        ],
      },
    ],
  ),
  exam("tsc-capstone-exam", "Фінальна контрольна", "Final exam", 3, [
    {
      id: "tsc-ce1",
      type: "mcq",
      promptUk: "TypeScript додає до JS:",
      promptEn: "TypeScript adds to JS:",
      options: ["static types", "GPU only", "SQL engine", "CSS parser"],
      correctIndex: 0,
    },
    {
      id: "tsc-ce2",
      type: "code_fill",
      promptUk: "Generic identity",
      promptEn: "Generic identity",
      language: "ts",
      code: "function id<T>(x: T): ___ { return x; }",
      accepted: ["T"],
      caseSensitive: true,
    },
    {
      id: "tsc-ce3",
      type: "code_fill",
      promptUk: "Partial utility",
      promptEn: "Partial utility",
      language: "ts",
      code: "type P = ___<User>;",
      accepted: ["Partial"],
      caseSensitive: true,
    },
    {
      id: "tsc-ce4",
      type: "mcq",
      promptUk: "Narrowing з typeof:",
      promptEn: "Narrowing with typeof:",
      options: ["sounds type", "unrelated", "only CSS", "deletes variable"],
      correctIndex: 0,
    },
    {
      id: "tsc-ce5",
      type: "code_fill",
      promptUk: "Union",
      promptEn: "Union",
      language: "ts",
      code: "type R = 'ok' ___ 'err';",
      accepted: ["|"],
      caseSensitive: true,
    },
  ]),
]);

export const typescriptContent: CourseContent = {
  slug: "typescript",
  titleUk: "TypeScript",
  titleEn: "TypeScript",
  descriptionUk:
    "Повний курс TypeScript: від примітивів до generics, narrowing і utility types. Контрольні після кожного розділу.",
  descriptionEn:
    "Full TypeScript course: primitives to generics, narrowing, and utility types. Unit exams after each section.",
  icon: "📘",
  color: "#3178C6",
  units: [
    basics,
    objects,
    interfaces,
    functions,
    generics,
    narrowing,
    utilities,
    modules,
    capstone,
  ],
};
