/** Achievement catalog codes — seeded into DB */

export type AchievementDef = {
  code: string;
  titleUk: string;
  titleEn: string;
  descriptionUk: string;
  descriptionEn: string;
  icon: string;
  xpReward: number;
};

export const ACHIEVEMENT_CATALOG: AchievementDef[] = [
  {
    code: "first_lesson",
    titleUk: "Перший крок",
    titleEn: "First step",
    descriptionUk: "Завершіть перший урок",
    descriptionEn: "Complete your first lesson",
    icon: "🌱",
    xpReward: 15,
  },
  {
    code: "lessons_10",
    titleUk: "Десятка",
    titleEn: "Ten lessons",
    descriptionUk: "Завершіть 10 уроків загалом",
    descriptionEn: "Complete 10 lessons total",
    icon: "📚",
    xpReward: 40,
  },
  {
    code: "streak_3",
    titleUk: "Серія 3",
    titleEn: "3-day streak",
    descriptionUk: "Тримайте серію 3 дні",
    descriptionEn: "Keep a 3-day streak",
    icon: "🔥",
    xpReward: 25,
  },
  {
    code: "streak_7",
    titleUk: "Тиждень вогню",
    titleEn: "Week of fire",
    descriptionUk: "Серія 7 днів",
    descriptionEn: "7-day streak",
    icon: "🔥",
    xpReward: 60,
  },
  {
    code: "level_5",
    titleUk: "Рівень 5",
    titleEn: "Level 5",
    descriptionUk: "Досягніть 5 глобального рівня",
    descriptionEn: "Reach global level 5",
    icon: "⭐",
    xpReward: 50,
  },
  {
    code: "daily_goal",
    titleUk: "Мета дня",
    titleEn: "Daily goal",
    descriptionUk: "Виконайте щоденну мету XP",
    descriptionEn: "Complete the daily XP goal",
    icon: "🎯",
    xpReward: 20,
  },
  {
    code: "english_path",
    titleUk: "Англійський шлях",
    titleEn: "English path",
    descriptionUk: "5 уроків англійської",
    descriptionEn: "5 English lessons",
    icon: "🇬🇧",
    xpReward: 30,
  },
  {
    code: "chess_player",
    titleUk: "Шахіст",
    titleEn: "Chess player",
    descriptionUk: "Зіграйте партію (online/бот/invite)",
    descriptionEn: "Play a chess game",
    icon: "♟️",
    xpReward: 25,
  },
  {
    code: "social_learner",
    titleUk: "Соціальний учень",
    titleEn: "Social learner",
    descriptionUk: "Приєднайтесь до класу школи",
    descriptionEn: "Join a school class",
    icon: "🏫",
    xpReward: 20,
  },
  {
    code: "tournament_entry",
    titleUk: "Учасник турніру",
    titleEn: "Tournament entrant",
    descriptionUk: "Запишіться на турнір",
    descriptionEn: "Join a tournament",
    icon: "🏁",
    xpReward: 25,
  },
  {
    code: "code_first_lesson",
    titleUk: "Hello, code",
    titleEn: "Hello, code",
    descriptionUk: "Завершіть перший урок Programming",
    descriptionEn: "Complete first Programming lesson",
    icon: "💻",
    xpReward: 20,
  },
  {
    code: "code_lessons_5",
    titleUk: "Кодер-стажер",
    titleEn: "Junior coder",
    descriptionUk: "5 уроків Programming",
    descriptionEn: "5 Programming lessons",
    icon: "⌨️",
    xpReward: 35,
  },
  {
    code: "code_lessons_15",
    titleUk: "Path builder",
    titleEn: "Path builder",
    descriptionUk: "15 уроків Programming",
    descriptionEn: "15 Programming lessons",
    icon: "🛤️",
    xpReward: 60,
  },
  {
    code: "pg_first_challenge",
    titleUk: "Playground noob",
    titleEn: "Playground noob",
    descriptionUk: "Розв'яжіть 1 playground challenge",
    descriptionEn: "Solve 1 playground challenge",
    icon: "🖥️",
    xpReward: 15,
  },
  {
    code: "pg_challenges_5",
    titleUk: "Challenge hunter",
    titleEn: "Challenge hunter",
    descriptionUk: "5 playground challenges",
    descriptionEn: "5 playground challenges",
    icon: "🎯",
    xpReward: 40,
  },
  {
    code: "pg_challenges_10",
    titleUk: "Sandbox master",
    titleEn: "Sandbox master",
    descriptionUk: "10 playground challenges",
    descriptionEn: "10 playground challenges",
    icon: "🏆",
    xpReward: 70,
  },
  {
    code: "code_mini_3",
    titleUk: "Mini builder",
    titleEn: "Mini builder",
    descriptionUk: "3 mini-projects у Programming",
    descriptionEn: "3 Programming mini-projects",
    icon: "🧩",
    xpReward: 40,
  },
  {
    code: "code_mini_all",
    titleUk: "Full stack minis",
    titleEn: "Full stack minis",
    descriptionUk: "Усі mini-projects Programming path",
    descriptionEn: "All Programming path mini-projects",
    icon: "🏗️",
    xpReward: 100,
  },
  {
    code: "code_minis_race_run",
    titleUk: "Minis racer",
    titleEn: "Minis racer",
    descriptionUk: "Візьми участь у тижневій minis-гонці (1+ mini)",
    descriptionEn: "Join a weekly minis race (complete 1+ featured mini)",
    icon: "🏁",
    xpReward: 20,
  },
  {
    code: "code_minis_race_podium",
    titleUk: "Minis podium",
    titleEn: "Minis podium",
    descriptionUk: "Топ-3 у тижневій minis-гонці",
    descriptionEn: "Top 3 in weekly minis race",
    icon: "🥉",
    xpReward: 45,
  },
  {
    code: "code_minis_race_win",
    titleUk: "Minis champion",
    titleEn: "Minis champion",
    descriptionUk: "1 місце у тижневій minis-гонці",
    descriptionEn: "1st place in weekly minis race",
    icon: "🥇",
    xpReward: 80,
  },
];
