/**
 * Routes that use RSC shell + client island pattern.
 * Keep in sync when adding strangler migrations.
 */
export const RSC_SHELL_ROUTES = [
  "/",
  "/pricing",
  "/login",
  "/register",
  "/forgot-password",
  "/reset-password",
  "/verify-email",
  "/courses",
  "/courses/[slug]",
  "/courses/[slug]/lessons/[lessonId]",
  "/search",
  "/dashboard",
  "/learn",
  "/leaderboard",
  "/challenges",
  "/achievements",
  "/quests",
  "/friends",
  "/play",
  "/flashcards",
  "/flashcards/[deckId]",
  "/review",
  "/certificates",
  "/certificates/[code]",
  "/u/[userId]",
  "/embed/playground",
  "/programming",
  "/programming/tree",
  "/programming/[stack]",
  "/profile",
  "/playground",
  "/shop",
  "/tutor",
  "/bookmarks",
  "/portfolio",
  "/homework",
  "/teacher",
  "/parents",
  "/parents/child/[studentId]",
  "/family",
  "/notes",
  "/focus",
  "/calendar",
  "/feedback",
  "/export",
  "/referrals",
  "/reports",
  "/placement",
  "/placement/programming",
  "/tournaments",
  "/tournaments/[id]",
  "/schools",
  "/schools/[id]",
  "/schools/class/[classId]",
  "/classroom/live/[classId]",
  "/studio/node",
  "/typescript",
  "/html-semantics",
  "/css-layout",
  "/qa-theory",
  "/js-fundamentals",
  "/react-fundamentals",
  "/sql-fundamentals",
  "/node-fundamentals",
  "/express-fundamentals",
  "/embedded-cpp",
  "/admin",
  "/admin/metrics",
  "/admin/users",
  "/admin/content",
  "/admin/courses",
  "/admin/feedback",
  "/admin/audit",
  "/admin/billing",
  "/admin/security",
  "/admin/appearance",
  "/admin/engagement",
  "/admin/classroom",
  "/admin/parents",
  "/admin/programming",
] as const;

const EXACT = new Set([
  "/",
  "/pricing",
  "/login",
  "/register",
  "/forgot-password",
  "/reset-password",
  "/verify-email",
  "/courses",
  "/search",
  "/dashboard",
  "/learn",
  "/leaderboard",
  "/challenges",
  "/achievements",
  "/quests",
  "/friends",
  "/play",
  "/flashcards",
  "/review",
  "/certificates",
  "/embed/playground",
  "/programming",
  "/programming/tree",
  "/profile",
  "/playground",
  "/shop",
  "/tutor",
  "/bookmarks",
  "/portfolio",
  "/homework",
  "/teacher",
  "/parents",
  "/family",
  "/notes",
  "/focus",
  "/calendar",
  "/feedback",
  "/export",
  "/referrals",
  "/reports",
  "/placement",
  "/placement/programming",
  "/tournaments",
  "/schools",
  "/studio/node",
  "/typescript",
  "/html-semantics",
  "/css-layout",
  "/qa-theory",
  "/js-fundamentals",
  "/react-fundamentals",
  "/sql-fundamentals",
  "/node-fundamentals",
  "/express-fundamentals",
  "/embedded-cpp",
  "/admin",
  "/admin/metrics",
  "/admin/users",
  "/admin/content",
  "/admin/courses",
  "/admin/feedback",
  "/admin/audit",
  "/admin/billing",
  "/admin/security",
  "/admin/appearance",
  "/admin/engagement",
  "/admin/classroom",
  "/admin/parents",
  "/admin/programming",
]);

export function isRscShellRoute(pathname: string): boolean {
  const p = pathname.replace(/\/$/, "") || "/";
  if (EXACT.has(p)) return true;
  if (p.startsWith("/certificates/") && p !== "/certificates") return true;
  if (p.startsWith("/u/") && p.length > 3) return true;
  if (p.startsWith("/flashcards/") && p !== "/flashcards") return true;
  if (p.startsWith("/courses/") && p !== "/courses") return true;
  if (p.startsWith("/programming/") && p !== "/programming" && p !== "/programming/tree") return true;
  if (p.startsWith("/tournaments/") && p !== "/tournaments") return true;
  if (p.startsWith("/schools/") && p !== "/schools") return true;
  if (p.startsWith("/parents/child/")) return true;
  if (p.startsWith("/classroom/live/")) return true;
  if (p.startsWith("/admin/")) return true;
  return false;
}
